### ISSUE TITLE
Wochentag und Datum

### ISSUE THREAD

**Issue by lapidu** [klein0r/ioBroker.trashschedule#1]
Hallo Matthias,

danke erstmal für den tollen Adapter.
Wäre es Möglich noch 2 Datenpunkte zu erstellen? 
Einmal mit dem nächsten Wochentag, und einmal mit dem nächsten Datum TT.MM.JJJJ

Danke

**Comment by klein0r** [comment]
Das Datum hast Du ja schon in einem Datenpunkt - einfach umformatieren wie Du es brauchst. Den Wochentag kann ich gerne noch einfügen

**Comment by lapidu** [comment]
Das wäre super.
Hast du einen Tipp wie ich das Datum umformatieren kann?

**Comment by klein0r** [comment]
Ich habe den Wochentag als Zahl eingefügt und das Datum formatiert. Das Format geben die globalen Einstellungen vor. Also DD.MM.YYYY oder DD/MM/YYYY

- 0 - Sonntag
- 1 - Montag
- 2 - Dienstag
- 3 - Mittwoch
- 4 - Donnerstag
- 5 - Freitag
- 6 - Samstag
