### ISSUE TITLE
VIS Widget anpassen

### ISSUE THREAD

**Issue by Ceel84** [klein0r/ioBroker.trashschedule#11]
Ist es möglich das das Widget in der Vis in der Größe anpassbar wird?
Ich bekomme es leider nicht kleiner weil dann einer der vier Mülleimer nach unten rutscht!

**Comment by klein0r** [comment]
Ist geplant das einzubauen, aber das wird noch etwas dauern. Pull Requests sind natürlich immer willkommen 😄

**Comment by Ceel84** [comment]
Würde ich gerne machen! Kenne mich nur leider nicht aus!
