### ISSUE TITLE
Abhängigkeit zur Version des Adminadapters wird falsch aufgelöst seit Version 1.4.5

### ISSUE THREAD

**Issue by bwilberg** [klein0r/ioBroker.trashschedule#111]
### The problem

Hi Matthias,
ich habe eine Problem seit der Version 1.4.5. Dort ist eine Abhängigkeit zum Admin-Adapter eingefügt worden. Mein Admin-Adapter ist aktuell auf Version 5.3.8. Der Trashschedule Adapter startet allerdings nicht, da er sagt, ich hätte eine Version < 5.3.2.
Kann ich dir irgendwelche weiteren Logs etc. geben? Kann es an meiner iobroker-Installation liegen? Ich kann mir nicht vorstellen, dass es ein Problem mit deinem Adapter ist, sonst würde das Problem ja schon aufgefallen sein.
Viele Grüße,
Bernd

### Version of nodejs

v14.19.3

### Version of ioBroker js-controller

4.0.23

### Version of Adapter

>=1.4.5

### Operating system running ioBroker

Docker (buanet)

### Checklist of files to include below

- [X] iobroker.current.log (Please share the logs in debug mode)
- [ ] Contents of the JavaScript browser console (always include in cases of issues with the user interface)

### Additional information & file uploads

startInstance system.adapter.trashschedule.0 Adapter dependency not fulfilled on any host: required adapter "admin" has wrong version. Installed "5.3.1", required ">=5.3.2"!
![Screenshot 2022-06-02 183042](https://user-images.githubusercontent.com/36631551/171679418-bbc8e59c-dbcc-4e22-acb5-e6e6d3fee5c8.png)

**Comment by klein0r** [comment]
Die Meldung kommt [vom js-controller](https://github.com/ioBroker/ioBroker.js-controller/blob/ea1a72ac2d74317ad16234f7aeac90632374614c/packages/controller/main.js#L3556-L3564). Und wenn der sagt, dass die Version falsch ist, dann müsste er hier auch die falsch Version zurückliefern:

``iobroker version admin``

Im Zweifel mal den ioBroker stoppen und neu starten. Als Adapter-Entwickler habe ich keinen Einfluss darauf, wie die Checks durchgeführt werden. Ich kann die nur definieren.

**Comment by klein0r** [comment]
Generell aber bitte ein Update auf die aktuellste stable machen (aktuell 2.0.2)

**Comment by bwilberg** [comment]
Danke für die schnelle Antwort. Ich habe den kompletten Dockercontainer schon neu gestartet. `iobroker version admin` liefert mir Version 5.3.8. 
Alle Adapterversion > 1.43 funktionieren auf Grund des nicht funktionierenden Versionscheck leider nicht. Echt seltsam.

**Comment by Apollon77** [comment]
iob upload admin 

fixed then?

**Comment by klein0r** [comment]
@Apollon77 Correct me if I'm wrong: That message is generated by the js-controller, which tries to start a new instance. The admin is not involved here.

**Comment by Apollon77** [comment]
Exactly. Here it seems that meta data went out of sync (maybe an restore on a newsly installed system where admin had older version in the backup - and restore was done using js.controller <4 :-)

**Comment by klein0r** [comment]
@bwilberg Solved? This is definitely not an issue of this adapter. It is caused by admin or js-controller.

**Comment by bwilberg** [comment]
@klein0r, @Apollon77: Thanks for your support. I couldn't fix it but now I know that this issue is not connected to Matthias adapter. I'll search for a reason why my installation does not report the installed version of the admin module.
So please close this bug report.
Best regards,
Bernd

**Comment by Apollon77** [comment]
@bwilberg Did you do a "iob upload admin" and tried again? Or did I missed the feedback on this?

**Comment by bwilberg** [comment]
@Apollon77 Yes, also tried an iob fix. I also restarted my docker container.

**Comment by Apollon77** [comment]
Do you read what I write??? I asked you to execute 

`iob upload admin`

I did not told anythiong about iob fix or restarts, just this one command

**Comment by bwilberg** [comment]
Sorry, my short „yes“ should mean that I did your suggestion to run `iob upload admin`
That didn‘t help.

**Comment by Apollon77** [comment]
Ok, then it starts getting weird ... completely off toipic here .... but please check which version is staed in /op/iobroker/node_modules/iobroker.admin/io-package.json and ideally also tyr again iob upload admin and show the console output

**Comment by bwilberg** [comment]
Hi @Apollon77, here are the first lines of io-package.json:
`root@iobroker:/opt/iobroker# cat /opt/iobroker/node_modules/iobroker.admin/io-package.json
{
  "common": {
    "name": "admin",
    "version": "5.3.8",
    "titleLang": {
      "en": "Admin",
      "de": "Admin",
      "ru": "Админ",
      "pt": "Admin",
      "pl": "Admin",
      "fr": "Admin",
      "nl": "Admin",
      "it": "Admin",
      "es": "Admin",
      "zh-cn": "Admin"
    },`

and from iob upload admin:

`root@iobroker:/opt/iobroker# iob upload admin
upload [14] admin.admin /opt/iobroker/node_modules/iobroker.admin/admin/admin.png admin.png image/png
upload [13] admin.admin /opt/iobroker/node_modules/iobroker.admin/admin/i18n/de/translations.json i18n/de/translations.json application/json
upload [12] admin.admin /opt/iobroker/node_modules/iobroker.admin/admin/i18n/en/translations.json i18n/en/translations.json application/json
upload [11] admin.admin /opt/iobroker/node_modules/iobroker.admin/admin/i18n/es/translations.json i18n/es/translations.json application/json
upload [10] admin.admin /opt/iobroker/node_modules/iobroker.admin/admin/i18n/fr/translations.json i18n/fr/translations.json application/json
upload [9] admin.admin /opt/iobroker/node_modules/iobroker.admin/admin/i18n/it/translations.json i18n/it/translations.json application/json
upload [8] admin.admin /opt/iobroker/node_modules/iobroker.admin/admin/i18n/nl/translations.json i18n/nl/translations.json application/json
upload [7] admin.admin /opt/iobroker/node_modules/iobroker.admin/admin/i18n/pl/translations.json i18n/pl/translations.json application/json
upload [6] admin.admin /opt/iobroker/node_modules/iobroker.admin/admin/i18n/pt/translations.json i18n/pt/translations.json application/json
upload [5] admin.admin /opt/iobroker/node_modules/iobroker.admin/admin/i18n/ru/translations.json i18n/ru/translations.json application/json
upload [4] admin.admin /opt/iobroker/node_modules/iobroker.admin/admin/i18n/zh-cn/translations.json i18n/zh-cn/translations.json application/json
upload [3] admin.admin /opt/iobroker/node_modules/iobroker.admin/admin/index.html index.html text/html
upload [2] admin.admin /opt/iobroker/node_modules/iobroker.admin/admin/index_m.html index_m.html text/html
upload [1] admin.admin /opt/iobroker/node_modules/iobroker.admin/admin/jsonConfig.json jsonConfig.json application/json
upload [0] admin.admin /opt/iobroker/node_modules/iobroker.admin/admin/words.js words.js application/javascript`

**Comment by Apollon77** [comment]
Do you have a multihost system? If yes ... do we talk about the admin version pot on "this host"?

**Comment by bwilberg** [comment]
Hi @Apollon77,
yes, I have a small child host. Both are running 5.3.8. We are talking about the master instance.
I tried to reinstall admin with `npm install admin` and found out that I had two missing dependencies for the admin module (buffer and tough-cookie).
After installing the two dependencies I could install the admin module again.
But this also did not fix the issue.

**Comment by Apollon77** [comment]
Please execute also ion upload admin on the second host and check Version in io-Package as well please.

**Comment by bwilberg** [comment]
Yes! You've found it! The admin version on my slave host was 5.3.8 in the web gui. Inside the json file it was 5.3.1. I just reinstalled the version 5.3.8 on my slave and after that Matthias module loaded fine on my master. So the version of the admin instance on all hosts seems to be relevant for the dependency inside the modules.
Thanks a lot for your help!

**Comment by Apollon77** [comment]
Yes, the "smalles version is the worst" and so the check uses this because it do not know which version is really in effect and could be used to configure it ...
