### ISSUE TITLE
Abfallarten sind keine Änderungen möglich wie Schreibgeschützt V 2.0.3

### ISSUE THREAD

**Issue by rabbit6984** [klein0r/ioBroker.trashschedule#123]
### The problem

Keine Änderungen im Register Abfalltypen
Hier kann lediglich mit + oder - eine Zeile hinzugefügt oder gelöscht werden.
Alles andeere Text Farbe Checkboxen ist wie schreibgeschützt.

Siehe Forum: https://forum.iobroker.net/topic/27050/test-adapter-trashschedule/1209?_=1657797769467

### Version of nodejs

16.60

### Version of ioBroker js-controller

4.0.23

### Version of Adapter

2.0.3

### Operating system running ioBroker

raspberry

### Checklist of files to include below

- [ ] iobroker.current.log (Please share the logs in debug mode)
- [ ] Contents of the JavaScript browser console (always include in cases of issues with the user interface)

**Comment by klein0r** [comment]
Ist wohl ein Admin 6.2.x Bug. Siehe https://github.com/ioBroker/ioBroker.admin/issues/1589
