### ISSUE TITLE
Bioabfall wird nicht immer erkannt

### ISSUE THREAD

**Issue by fraenki57** [klein0r/ioBroker.trashschedule#124]
### The problem

Moin, Matthias,
seit Frühling, wo der Bioabfall jede Woche abgeholt wird, wird bei mir "Bioabfall" im Kalender manchmal nicht erkannt (so wie z.B. kommenden Montag, 18.7.). Vorher war es wohl nicht aufgefallen wegen des 2-Wochen-Rhythmus (oder weil ich nicht darauf geachtet habe)
Bioabfall wird korrekt erkannt im Kalender beim String "Bioabfall Wertstofftonne" (11.7.)
Bioabfall wird *nicht* erkannt im Kalender beim String "Restabfall Bioabfall" (18.7.)
Ob er 2 Wochen weiter bei "Restabfall Bioabfall Papier / Pappe" auch nicht erkannt wird, kann ich im Moment ja noch nicht sehen.
Sieht für mich (selbst SW-Entwickler) irgendwie zunächst so aus, als ob Bioabfall nicht erkannt wird, wenn er nicht an erster Stelle steht. Kann natürlich andere Gründe haben ...
Alle anderen Abfallarten werden immer korrekt erkannt, nur eben mit Bioabfall gibt es scheinbar Probleme.
Der Kalender befindet sich auf einer NextCloud-Instanz auf meinem Raspi:

![Kalender-Screenshot](https://user-images.githubusercontent.com/76413614/179073139-4d215102-1fd9-4a3e-9718-cdefe735c04e.jpg)

Ein Screenshot der VIS mit TrashSchedule und dem falschen Bioabfalldatum stelle ich dir auch mal zur Verfügung:

![vis](https://user-images.githubusercontent.com/76413614/179074078-71288671-4fc1-4757-927a-e9d5c6d54c4b.jpg)

Die originale ics-Datei kann mit der Extension hier nicht hochladen, kann ich dir aber bei Bedarf gerne auf anderem Wege zur Verfügung stellen.

Ich sehe nicht, dass ich irgendwo was falsch konfiguriert habe, außerdem funktioniert es ja meistens.
In der Version 2.0.3 ist laut Release-Notes was anderes geändert worden, daher habe ich das nicht ausprobiert.

Falls du noch weitere Infos braucht, melde dich einfach.

Gruß Frank

### Version of nodejs

v14.20.0

### Version of ioBroker js-controller

4.0.23

### Version of Adapter

2.0.2

### Operating system running ioBroker

Linux (Raspian)

### Checklist of files to include below

- [X] iobroker.current.log (Please share the logs in debug mode)
- [ ] Contents of the JavaScript browser console (always include in cases of issues with the user interface)

### Additional information & file uploads

Im Logfile sehe ich keine TrashSchedule-Einträge.

**Comment by klein0r** [comment]
Ich soll jetzt anhand von 2 Screenshots beurteilen was da schief läuft? Sehr schwierig. Stell die Instanz auf debug log level und teile das Log + deine Konfiguration. Ich wette es ist kein Issue und ich mache mal wieder Support hier 😄

**Comment by fraenki57** [comment]
Moin,
ich ziehe mein Request zurück, kann geschlossen werden.
Den Debug Loglevel hatte ich aktiviert und es tauchten keine Einträge auf (wie beschrieben). Mir war bis eben nicht bekannt, dass es noch einen Level "silly" gibt ... da habe ich dann sofort die Ursache erkannt. Du hast also die Wette gewonnen. Sorry für mein Unwissen hier ... Support zu erhalten, war nicht meine Absicht. Danke für deine viele Arbeit mit TrashSchedule.

**Comment by klein0r** [comment]
Alles gut, nur bitte in Zukunft immer möglichst viele Informationen mitliefern, sodass man wirklich schauen kann, was passiert. Du hast ja auch beim Issue anlegen angehakt, dass ein Debug-Log mitgeliefert wird (was nicht passiert ist).
Das wäre so, als ob Du einem Mechaniker ein Foto von deinem Auto schickst und sagst "es ruckelt im dritten Gang - was kann das sein"?
