### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by Siggi0904** [klein0r/ioBroker.trashschedule#145]
### The problem

Hallo,

da unser Abfallunternehmen noch keine Termine für 2023 draußen hat, laufen aktuell Warnmeldungen auf. Z.B.:
`no events matches type "Papier" with match "Papier" (exact match)`

Könnte eine Option zur Deaktivierung eines Kalenders/abfalltyps hinzugefügt werden?

Danke.

### Version of nodejs

v16.18.1

### Version of ioBroker js-controller

6.0.3

### Version of Adapter

2.0.3

### Operating system running ioBroker

Debian

### Checklist of files to include below

- [X] iobroker.current.log (Please share the logs in debug mode)
- [ ] Contents of the JavaScript browser console (always include in cases of issues with the user interface)

### Additional information & file uploads

`trashschedule.0 | 2022-12-12 20:00:16.730 | warn | no events matches type "Papier" with match "Papier" (exact match)`

**Comment by klein0r** [comment]
> Könnte eine Option zur Deaktivierung eines Kalenders/abfalltyps hinzugefügt werden?

Du kannst pro Typ die Warnungen deaktivieren. Das wurde schon vor langer Zeit für z.B. Weihnachtsbäume eingeführt.
