### ISSUE TITLE
Vis Template wird nicht auf Mobilgeräten angezeigt

### ISSUE THREAD

**Issue by Tickle75** [klein0r/ioBroker.trashschedule#15]
Ich habe das Problem dass das Template auf meinem Browser angezeigt wird (Firefox 74.0), auf Vis Mobile aber nicht. Sowohl auf meinem Huawei P20 (EMUI 9.1.0.380 / Vis 1.1.1) als auch auf meinem Lenovo Yoga 2-1050F (Android 5.01 / Vis 1.0.0) wird es nicht angezeigt.

**Comment by klein0r** [comment]
Nutzt Du die VIS App oder einen Browser?

**Comment by Tickle75** [comment]
auf den Mobilgeräten nutze ich die Vis App.

**Comment by klein0r** [comment]
Okay, das liegt daran, dass die einzelnen Widgets in der App wohl irgendwie hinterlegt werden müssen. Darauf habe ich nur keinen Zugriff und kenne den genauen Prozess auch nicht. Also ist das ein Issue für die VIS App - ich kann da leider nichts machen

**Comment by Tickle75** [comment]
Ok, trotzdem ein Danke für den tollen Adapter.

**Comment by klein0r** [comment]
Tut mir leid, dass ich hier nicht mehr tun kann
