### ISSUE TITLE
Parsing events with „/„ doesn’t work?

### ISSUE THREAD

**Issue by Eldron81** [klein0r/ioBroker.trashschedule#151]
### The problem

Hi! Thanks for great work.

There is an issue parsing one event type with an „/„ in the title. Our local trash company provides the calendar events via iCal, 3 out of 4 trash types work just fine. Only for Gelbe Tonne/Gelben Sack the events could not be read.

Log warning: no events matches type "GelbeTonne" with match "Gelbe Tonne/Gelben Sack"

I have tried to reduce the match phrase to parts without „/„, not working. Since the other events work just fine I assume the issue is the slash and it already appears during reading of the events?

Happy to prove any additional information to help.

### Version of nodejs

16.19.0

### Version of ioBroker js-controller

4.0.24

### Version of Adapter

2.1.1

### Operating system running ioBroker

linux on pi

### Checklist of files to include below

- [X] iobroker.current.log (Please share the logs in debug mode)
- [ ] Contents of the JavaScript browser console (always include in cases of issues with the user interface)

### Additional information & file uploads

no events matches type "GelbeTonne" with match "Gelbe Tonne/Gelben Sack"

**Comment by Eldron81** [comment]
I manually changed some events and deleted the "/", still doesn't work. Could it be a problem with iCal?

**Comment by klein0r** [comment]
Please share the debug log file...

**Comment by Eldron81** [comment]
Hi! Klappt das, wenn ich im Expert Mode auf den Upload Pfeil drücke?
Falls nicht:
[trashschedule.log](https://github.com/klein0r/ioBroker.trashschedule/files/10419952/trashschedule.log)

PS: Ich komme aus der Region Hannover, viel Hochdeutscher wird es nicht ;). Und da wir je nach Region mal eine Tonne mal einen Sack / eine Tüte haben hat sich "Den gelben Sack abholen" im Sprachgebraucht eingebürgert. Du hast aber natürlich recht, auch hier ist es "Der gelbe Sack". Habe teilweise nur Satzteile entfernt um zu testen.

**Comment by klein0r** [comment]
> Ich komme aus der Region Hannover, viel Hochdeutscher wird es nicht

So war das nicht gemeint, klang nur nach Typo, weil ich dort "gelber Sack" erwartet hätte.

Zum Log:

Es werden ja auch nur 3 Einträge durchsucht.

- `Restmülltonne wird abgeholt.`
- `Bio-Tonne wird abgeholt.`
- `Papiermülltonne wird abgeholt.`

Mehr ist nicht enthalten. Nix mit gelben Säcken. Daher auch der Hinweis im Log.

> 2023-01-15 11:13:02.042 - info: trashschedule.0 (19132) [ical] configurured ical preview is 7 days - increase this value to find more events in the future

**Comment by Eldron81** [comment]
Alles gut... 😄.

Jetzt wird es allerdings spannend mit dem gelben Sack. Warum wurde er nicht durchsucht?

Heute hat er nämlich den gelben Sack gefunden, dafür sagt er Papier und Restmüll fehlen. Restmüll war heute Morgen, Papier ist am Freitag und sollte auf jeden auftauchen?

Entsprechend sind die Objekte "next" bei beiden frei. Bin ich nicht in der Lage das Tool richtig zu konfigurieren oder woran kann das liegen? Danke für deine Zeit!

**Comment by klein0r** [comment]
Wie schon geschrieben: Schau immer ins Log. Da wird genau beschrieben was für Schritte durchgeführt werden.

**Comment by Eldron81** [comment]
RTFM... habs gefunden. Ich habe wohl in der Beschreibung überlesen das die Kalender in iCal auf anzeigen stehen müssen. Warum deshalb nur teilweise bestimmte Events ausgeblendet wurden verstehe ich zwar noch immer nicht - aber mit "anzeigen" kommen alle Termine durch.

Danke für den Support!

**Comment by klein0r** [comment]
> das die Kalender in iCal auf anzeigen stehen müssen

Die Ereignisse müssen auf "anzeigen" stehen. Sonst werden die Events (welche für die Ereignisse treffen) von iCal aus der Termin-Liste gelöscht und andere Adapter haben da keinen Zugriff mehr drauf. Sollte aber auch einen entsprechenden Hinweis im Log geben, wenn ein Ereignis nicht auf "anzeigen" steht.
