### ISSUE TITLE
VIS Widget - Nur eine (erste) Mülltonne sichtbar

### ISSUE THREAD

**Issue by derChaos** [klein0r/ioBroker.trashschedule#16]
Beim einpflegen der JSON wird mir im VIS nur eine Mülltonne angezeigt (die erste) alle anderen angelegten Mülltonnen sind nicht sichtbar. 
Öffne ich das JSON mit einer Table sind alle Daten sichtbar

**Installationsroutine*
Ausgeführt wie in der Anleitung auf deinem YT Channel

*Einstellungen im iCal.1* 
![iCal_01_config_page_1](https://user-images.githubusercontent.com/62850085/77856825-1ec1c700-71fa-11ea-919c-4ffabaafd39e.JPG)

![iCal_01_config_page_2](https://user-images.githubusercontent.com/62850085/77856834-27b29880-71fa-11ea-94b2-ada3e28d23e0.JPG)

Keine Ereignisse

![trash_schedule_config_page_1](https://user-images.githubusercontent.com/62850085/77856764-abb85080-71f9-11ea-8a3a-1ab79a221083.JPG)

![trash_schedule_config_page_2](https://user-images.githubusercontent.com/62850085/77856768-b246c800-71f9-11ea-83de-ef7a9cfeaba8.JPG)

**Expected behavior**  
Läuft

**Screenshots & Logfiles**  
![trash_schedule](https://user-images.githubusercontent.com/62850085/77856616-a6a6d180-71f8-11ea-8f50-bf70369ec7b3.JPG)

*Widget Export*
`[{"tpl":"tplTrashscheduleHelper","data":{"g_fixed":false,"g_visibility":false,"g_css_font_text":false,"g_css_background":false,"g_css_shadow_padding":false,"g_css_border":false,"g_gestures":false,"g_signals":false,"g_last_change":false,"visibility-cond":"==","visibility-val":1,"visibility-groups-action":"hide","signals-cond-0":"==","signals-val-0":true,"signals-icon-0":"/vis/signals/lowbattery.png","signals-icon-size-0":0,"signals-blink-0":false,"signals-horz-0":0,"signals-vert-0":0,"signals-hide-edit-0":false,"signals-cond-1":"==","signals-val-1":true,"signals-icon-1":"/vis/signals/lowbattery.png","signals-icon-size-1":0,"signals-blink-1":false,"signals-horz-1":0,"signals-vert-1":0,"signals-hide-edit-1":false,"signals-cond-2":"==","signals-val-2":true,"signals-icon-2":"/vis/signals/lowbattery.png","signals-icon-size-2":0,"signals-blink-2":false,"signals-horz-2":0,"signals-vert-2":0,"signals-hide-edit-2":false,"lc-type":"last-change","lc-is-interval":true,"lc-is-moment":false,"lc-format":"","lc-position-vert":"top","lc-position-horz":"right","lc-offset-vert":0,"lc-offset-horz":0,"lc-font-size":"12px","lc-font-family":"","lc-font-style":"","lc-bkg-color":"","lc-color":"","lc-border-width":"0","lc-border-style":"","lc-border-color":"","lc-border-radius":10,"lc-zindex":0,"oid":"trashschedule.0.type.json"},"style":{"left":"546px","top":"146px","width":"580px","height":"250px"},"widgetSet":"trashschedule"}]`

*Inhalt der JSON*

`[{"name":"Papiertonne","daysleft":1,"nextdate":"2020-03-29T22:00:00.000Z","_color":"#2E64FE"},{"name":"Restmülltonne","daysleft":3,"nextdate":"2020-03-31T22:00:00.000Z","_color":"#00000"},{"name":"Biotonne","daysleft":3,"nextdate":"2020-03-31T22:00:00.000Z","_color":"#800000"},{"name":"Gelber Sack","daysleft":8,"nextdate":"2020-04-05T22:00:00.000Z","_color":"#FFFF00"}]`

**Versions:**  
 - Adapter version: 0.0.5
 - JS-Controller version: 10.19.0
 - Node version: 6.13.7
 - Operating system: RaspberryPi / Linux

**Additional context**  
-/-

**Comment by klein0r** [comment]
Die Farben der Tonnen werden jetzt automatisch korrigiert. Sollte ab Version 0.0.7 nicht mehr so fehleranfällig sein.
