### ISSUE TITLE
Adapter Meldet kein Match

### ISSUE THREAD

**Issue by BenAhrdt** [klein0r/ioBroker.trashschedule#169]
### The problem

Adapter meldet, dass kein Match für Blaue Tonne gefunden wird.
Seit heute bekomme ich diese Meldung (Adapter läuft so schon ewig und hat dies noch nie gemacht:

`<html>
<body>

trashschedule.0 | 2023-04-04 16:30:02.131 | warn | no events matches type "Blaue Tonne" with match "Blaue"
-- | -- | -- | --

</body>
</html>`

Kalender:
![image](https://user-images.githubusercontent.com/92173565/229827028-90e166b1-c5f8-44c5-bffb-eaad9457f9de.png)

Vielleicht, weil heute der Abfuhrtag ist?
Dies hatte ich auch noch nie
![image](https://user-images.githubusercontent.com/92173565/229827393-140c3abc-2ca2-4dc4-a675-d3c6551d2c13.png)

[iobroker.current.log](https://github.com/klein0r/ioBroker.trashschedule/files/11149764/iobroker.current.log)

### Version of nodejs

18.15.0

### Version of ioBroker js-controller

4.0.24

### Version of Adapter

2.2.0

### Operating system running ioBroker

docker linux (Buanet)

### Checklist of files to include below

- [X] iobroker.current.log (Please share the logs in debug mode)
- [ ] Contents of the JavaScript browser console (always include in cases of issues with the user interface)

**Comment by klein0r** [comment]
Debug-Log fehlt...

**Comment by BenAhrdt** [comment]
@klein0r der hat den als Link unter den Text eingefügt

**Comment by klein0r** [comment]
Ab 10 Uhr skipped er die heutigen Termine laut deiner Config. Log ist von 16:39 Uhr

**Comment by BenAhrdt** [comment]
Das sind die Einstellungen. Da sind schon mal die 10 Uhr zu sehen.
![image](https://user-images.githubusercontent.com/92173565/229980601-f9e290ac-87ee-4e7b-8584-59d80aff0559.png)

Wo kann ich denn die 30 Tage hoch setzen?
Ps. Heute macht er es nicht mehr, obwohl es noch mehr. Heute sind es genau 30Tage bis zur nächsten Leerung der Blauen Tonne,
