### ISSUE TITLE
Übersetzung und Textanpassung

### ISSUE THREAD

**Issue by thost96** [klein0r/ioBroker.trashschedule#17]
Hi, eine Übersetzung der Ausgabe "3 days" in "3 Tage" oder andere Sprachen entsprechend der im ioBroker ausgewählten Sprache oder konfigurierbar im Adapter wäre super. 

Zudem wäre es schön, wenn statt "1 days " der Text auf "1 Day" angepasst wird. 
Danke!

**Comment by klein0r** [comment]
Das ist eine Einheit, ich weiß gar nicht ob man die übersetzen und von der Anzahl abhängig machen kann. Muss ich mir anschauen

**Comment by klein0r** [comment]
Geht leider aktuell nicht. Sieht man aber auch nur im Admin unter Objekte - in der VIS kann man das ja entsprechend hinterlegen.
