### ISSUE TITLE
no events matches type 

### ISSUE THREAD

**Issue by docugraf** [klein0r/ioBroker.trashschedule#170]
### The problem

Seit ein paar Tagen erhalte ich unregelmäßig bei _einem_ von 4 Abfalltypen "| warn | no events matches type".

Es sind bis Jahres Ende für alle 4 Typen Termine hinterlegt, derzeit wird ical halbstündig ausgeführt, ca. 1/4 wird bearbeitet, wobei das dann eher blockweise passiert (heute war es von 08:30 bis 11:00 und 16:00 bis 18:00 ok,  zu den anderen Zeiten kommt die Fehlermeldung

Grad noch gesehen: in den Objekten gibt's keinen gültigen Eintrag zu zukünftigen Anholterminen

### Version of nodejs

v16.19.0 

### Version of ioBroker js-controller

4.0.24

### Version of Adapter

2,2,0

### Operating system running ioBroker

Linux 

### Checklist of files to include below

- [X] iobroker.current.log (Please share the logs in debug mode)
- [ ] Contents of the JavaScript browser console (always include in cases of issues with the user interface)

### Additional information & file uploads

`trashschedule.0 | 2023-05-19 22:00:05.065 | warn | no events matches type "Papiertonne" with match "Papier und Pappe"
trashschedule.0 | 2023-05-19 22:00:03.140 | warn | no events matches type "Papiertonne" with match "Papier und Pappe"
`

![grafik](https://github.com/klein0r/ioBroker.trashschedule/assets/104724022/cf4a52d2-e8e3-420b-9f3a-7ec938c86d6a)

**Comment by klein0r** [comment]
Bitte ein vollständiges Debug-Log teilen. Du hast garantiert etwas falsch konfiguriert...
Bis dahin mache ich hier zu

**Comment by lengerix** [comment]
Dear klein0r,

First of all I want to thank you for your Youtube-Videos & projects you are sharing with us.

I also experienced kind of the "same" issue as docugraf.

In my case the adapter  is set to:
![image](https://github.com/klein0r/ioBroker.trashschedule/assets/62711183/a2f7aed4-70a9-47dd-ac4d-daf5ebb34dbf)

My calendar entries are:
![image](https://github.com/klein0r/ioBroker.trashschedule/assets/62711183/09f298c9-8834-40a6-b485-e947b2ac3e1d)

According to the log, the entry "gelber Sack Alle" is not found/matching:
![image](https://github.com/klein0r/ioBroker.trashschedule/assets/62711183/89499889-3cae-49de-826f-a861b3424823)

The setting for "Genaue Übereinstimmung" is not selected, so the filter seems to be case sensitive.

Is this a adapter issue or do I missunderstand the settings ?

**Comment by klein0r** [comment]
> so the filter seems to be case sensitive.

yes, it was. Already fixed in 3.1.0

**Comment by lengerix** [comment]
Dear Matthias,

Thank you for your fast reply, I assume you meant 3.0.0 (latest release, yesterday)
![image](https://github.com/klein0r/ioBroker.trashschedule/assets/62711183/9d7f34ac-60d9-46a4-a6a9-05d7dba19fda)

I can confirm, after an update from 2.3.0 to 3.0.0 resolved the issue

**Comment by klein0r** [comment]
> I assume you meant 3.0.0 (latest release, yesterday)

No, 3.1.0 (latest release, today)

https://github.com/klein0r/ioBroker.trashschedule/blob/7a89063654cbf2f092c944ab587db085a7b4eba4/README.md?plain=1#L57-L60

**Comment by klein0r** [comment]
https://github.com/klein0r/ioBroker.trashschedule/releases/tag/v3.1.1
