### ISSUE TITLE
Problem mit dem Datum zweiten Tonne

### ISSUE THREAD

**Issue by fraaadl** [klein0r/ioBroker.trashschedule#18]
Beide Tonnen werden auf den 14.04. geplant. Wobei laut Google Kalender 🗓 der Restabfallbehälter erst am 20.04. dran wäre.

Google Kalender:
![image](https://user-images.githubusercontent.com/63262868/78603328-3a5f4a00-7858-11ea-81cb-7d218e7a8295.png)

Ical:
![image](https://user-images.githubusercontent.com/63262868/78603506-8dd19800-7858-11ea-84c8-cfa480484a8d.png)
![image](https://user-images.githubusercontent.com/63262868/78603547-9c1fb400-7858-11ea-8064-cd15e4ed2269.png)

Trashschedule:
![image](https://user-images.githubusercontent.com/63262868/78603410-637fda80-7858-11ea-8c48-e7d744fafd53.png)
![image](https://user-images.githubusercontent.com/63262868/78603426-6975bb80-7858-11ea-8c2c-4ef33919604f.png)

![image](https://user-images.githubusercontent.com/63262868/78603380-54992800-7858-11ea-8ff8-418c35b1e4a4.png)

Grüße

**Comment by klein0r** [comment]
Ich konnte das Problem nicht reproduzieren. Falls es nach wie vor besteht, sende mir bitte die iCal URL dazu.
