### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by Brainbug01** [klein0r/ioBroker.trashschedule#188]
### The problem

Admin V6.12.1 meldet beim öffnen des trashschedule Adapters:

```
trashschedule has an invalid jsonConfig: 
[{
"instancePath":"",
"schemaPath":"#/additionalProperties",
"keyword":"additionalProperties",
"params":{"additionalProperty":"iconPosition"},
"message":"must NOT have additional properties"
}]
```

### Version of nodejs

v18.18.2

### Version of ioBroker js-controller

5.0.15

### Version of Adapter

v2.3.0

### Operating system running ioBroker

Linux

### Checklist of files to include below

- [X] iobroker.current.log (Please share the logs in debug mode)
- [ ] Contents of the JavaScript browser console (always include in cases of issues with the user interface)

**Comment by klein0r** [comment]
https://github.com/ioBroker/adapter-react-v5/issues/197
