### ISSUE TITLE
Bitte Trashscheduler Widget in Android/iOS Widget Set integrieren

### ISSUE THREAD

**Issue by JBSullivan** [klein0r/ioBroker.trashschedule#19]
Unter den Mobilen Versionen der ioB Apps (Android/iOS) wird das Trashscheduler Widget nicht angezeigt.

Wie aus dem ioB Forum zu erfahren war, muss das seperat eingepflegt werden - siehe Kommentar Homoran ->

> in der Android App müssen alle Widgets eingepflegt werden, da NICHT die Widgets von jedem User, sondern ein einprogrammierter Satz verwendet wird. Bei iOS weiß ich es nicht

![2020-03-29 09_06_28-vis](https://user-images.githubusercontent.com/44617472/79118062-0f5f8380-7d8d-11ea-8b1f-51d4df483985.png)

![Screenshot_20200329_100623_net iobroker vis](https://user-images.githubusercontent.com/44617472/79118218-8bf26200-7d8d-11ea-9818-7cee9517873c.jpg)

**Comment by klein0r** [comment]
Weißt Du denn auch, wer die App pflegt und an wen man sich da wenden muss? Gibt es ein GitHub Repo?

**Comment by JBSullivan** [comment]
Das kann ich leider nicht sagen - wie gesagt, ich wurde von Homoran aufgefordert ein Ticket zu erstellen. Ich gehe davon aus, das er das hier bei Trashschedule meinte.

------------------------------------------------------------------------------------
@JB_Sullivan Das ist die aktuellste (seit 2 Tagen) App-Version.
Dann mache bitte ien Issue mit feature-Request für die Trashschedule widgets auf
-------------------------------------------------------------------------------------

**Comment by JBSullivan** [comment]
Hat sich bzgl. dieses Thema denn irgend etwas getan? Die Meldung ist ja hier geschlossen worden. Obwohl bei mir alles auf dem aktuellen Stand ist, wird unter Android das Widget immer noch nicht angezeigt. Beim PC via Remote Einwahl und iOS ist das Widget da, aber unter Android leider nicht - trotz aktueller Synchronisation.

**Comment by klein0r** [comment]
Da ich die App nicht entwickle, ist der Fehler im falschen Repo gemeldet. Da kann ich nichts dran machen. Ich denke, hier ist der richtige Platz:

https://github.com/ioBroker/ioBroker.vis.cordova/issues
