### ISSUE TITLE
Einrichtung funktioniert nicht

### ISSUE THREAD

**Issue by AlexanderSch90** [klein0r/ioBroker.trashschedule#2]
Hallo, ich würde den Adapter gerne nutzen, jedoch scheint es ein Problem zu geben, wie der Adapter die Infos einließt. 

Im Ical-Adapter habe ich den Müllkalender unter "Kalender" eingepflegt. Unter "Ereigisse" z.B. "Restabfall".

In deinem Adapter habe ich dann gesagt, er soll nach "Restabfall" suchen (Spalte "Gilt für Termine").

Alle Objekte werden angelegt und sind leer. 

Wenn ich den Adapter im Debug Modus öffne. Werden die Kalendereinträge von meinen anderen Kalendern "durchsucht". Er kommt jedoch nicht bis zum Müllkalender und findet deshalb nichts. Ich vermute er kommt mit den anderen Kalendern nicht klar. Hast du eine Idee wie ich zur Lösung komme?

Danke!

**Comment by klein0r** [comment]
Wieviele Tage im Voraus hast Du denn im iCal-Adapter konfiguriert? Häufig steht dort eine zu kleine Zahl drin, sodass dieses Module die Termine in der Zukunft gar nicht finden kann.

**Comment by AlexanderSch90** [comment]
90 Tage. Daran kann es (leider) nicht liegen.

**Comment by 5v3n-08** [comment]
Hallo Matthias
Ich habe ebenfalls das Problem das alle Objekte leer bleiben. Es sieht so aus als würde es an dem ical Adapter liegen. Die Daten vom Kalender nimmst du ja aus "ical.x.data.table" dieses ist bei mir allerdings leer und gib ein leeres Array zurück.

**Comment by klein0r** [comment]
Dass die Liste leer ist könnte daran liegen, dass im ical-Adapter unter "Events"/"Ereignisse" bereits Termine gefiltert werden. Sollten dort Einträge vorhanden sein, welche nicht den Haken bei "display"/"anzeigen" haben, dann bleibt die Termin-Liste eventuell leer.

Lösung: Bei allen Termin den Haken setzen oder die Liste komplett leeren.
