### ISSUE TITLE
Uhrzeit aus Termin wird nicht in die Objekte übernommen sondern immer  00:00:00 angezeigt

### ISSUE THREAD

**Issue by Feuer-sturm** [klein0r/ioBroker.trashschedule#20]
**Describe the bug**  
Ich habe vor kurzem die Einträge von meinem Müllkalender von ganztägige Ereignisse auf eine feste Uhrzeit umgestellt.
Im Google Kalender ist es wie folgt eingetragen:
![grafik](https://user-images.githubusercontent.com/25422320/79915134-b778ea80-8426-11ea-9dd3-b05609a5e73e.png)

Bei der ical1 Instanz steht im Datenpunkt auch das richtige drin: ical.1.data.html
![grafik](https://user-images.githubusercontent.com/25422320/79915166-c5c70680-8426-11ea-9b57-2efd2a1c4846.png)

Nur beim Adapter kommt die Uhrzeit leider nicht an. Hier wird in den Datenpunkten immer 00:00:00 angezeigt.
![grafik](https://user-images.githubusercontent.com/25422320/79915211-d8d9d680-8426-11ea-8347-9d850de0906c.png)
![grafik](https://user-images.githubusercontent.com/25422320/79915265-f444e180-8426-11ea-9742-3a4686b63291.png)

**Expected behavior**  
Die Erwartung ist, dass die Zeiten aus dem Termin auch in den Datenpunkten enthalten sind

**Versions:**  
 - Adapter version: 0.0.5
 - JS-Controller version: 2.2.10
 - Node version: v10.18.1
 - Operating system: ubuntu 18

**Additional context**  
Diskussion im ioBroker Forum: https://forum.iobroker.net/topic/27050/test-adapter-trashschedule-v0-0-x/289

**Comment by klein0r** [comment]
Das ist so gewollt, im Adapter wird immer der ganze Tag genommen und Start- und Endzeit des Termins ignoriert.
