### ISSUE TITLE
Bug report: Adapter V3.1.1. startet nicht mehr

### ISSUE THREAD

**Issue by Horgul123** [klein0r/ioBroker.trashschedule#207]
### The problem

Adpater V 3.1.1. wird anch dem Start nicht mehr grün.

Log:
`
trashschedule.0 | 2023-12-22 16:57:51.881 | info | terminating
-- | -- | -- | --
trashschedule.0 | 2023-12-22 16:57:51.380 | warn | Terminated (UNCAUGHT_EXCEPTION): Without reason
trashschedule.0 | 2023-12-22 16:57:51.380 | debug | Plugin sentry destroyed
trashschedule.0 | 2023-12-22 16:57:51.380 | info | terminating
trashschedule.0 | 2023-12-22 16:57:51.379 | info | cleaned everything up...
trashschedule.0 | 2023-12-22 16:57:51.254 | error | Not exists
trashschedule.0 | 2023-12-22 16:57:51.254 | error | Error: Not exists at Object.maybeCallbackWithError (/opt/iobroker/node_modules/@iobroker/js-controller-common/src/lib/common/maybeCallback.ts:136:17) at ObjectsInRedisClient._readDir (/opt/iobroker/node_modules/@iobroker/db-objects-redis/src/lib/objects/objectsInRedisClient.ts:1468:26) at processTicksAndRejections (node:internal/process/task_queues:95:5)
trashschedule.0 | 2023-12-22 16:57:51.131 | error | unhandled promise rejection: Not exists
trashschedule.0 | 2023-12-22 16:57:51.131 | error | Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
trashschedule.0 | 2023-12-22 16:57:50.302 | info | [ical] configurured ical preview is 31 days (until 08.01.2030) - increase this value to find more events in the future
trashschedule.0 | 2023-12-22 16:57:50.301 | debug | [ical] current ical version: 1.13.5
trashschedule.0 | 2023-12-22 16:57:47.587 | debug | found configured trash type: "Wertstoffe" with ID "type.wertstoffe"
trashschedule.0 | 2023-12-22 16:57:45.658 | debug | found configured trash type: "Biotonne" with ID "type.biotonne"
trashschedule.0 | 2023-12-22 16:57:45.658 | debug | found existing trash type with ID "type.wertstoffe"
trashschedule.0 | 2023-12-22 16:57:45.657 | debug | found existing trash type with ID "type.biotonne"
trashschedule.0 | 2023-12-22 16:57:44.399 | info | starting. Version 3.1.1 in /opt/iobroker/node_modules/iobroker.trashschedule, node: v18.18.2, js-controller: 5.0.17

`

Downgrade auf 3.1.0 nicht möglich:

`$ iobroker upgrade trashschedule@3.1.0 --debug

Update trashschedule from @3.1.1 to @3.1.0

NPM version: 9.8.1Installing iobroker.trashschedule@3.1.0... (System call)

npm ERR! code ETARGETnpm ERR! notarget No matching version found for iobroker.trashschedule@3.1.0.npm ERR! notarget In most cases you or one of your dependencies are requestingnpm ERR! notarget a package version that doesn't exist.

npm ERR! A complete log of this run can be found in: /home/iobroker/.npm/_logs/2023-12-22T16_01_00_943Z-debug-0.log

npm ERR! code ETARGETnpm ERR! notarget No matching version found for iobroker.trashschedule@3.1.0.npm ERR! notarget In most cases you or one of your dependencies are requestingnpm ERR! notarget a package version that doesn't exist.npm ERR! A complete log of this run can be found in: /home/iobroker/.npm/_logs/2023-12-22T16_01_00_943Z-debug-0.loghost.iobrokervm Cannot install iobroker.trashschedule@3.1.0: 1

ERROR: Process exited with code 25`

### Version of nodejs

v18.18.2

### Version of ioBroker js-controller

5.0.17

### Version of Adapter

3.1.1.

### Operating system running ioBroker

debian 12

### Checklist of files to include below

- [X] iobroker.current.log (Please share the logs in debug mode)
- [ ] Contents of the JavaScript browser console (always include in cases of issues with the user interface)

### Additional information & file uploads

.Log too big

**Comment by Negalein** [comment]
same problem here

**Comment by PalmManiac** [comment]
Gleiches Problem hier seit dem Update heute auf V3.1.1

**Comment by klein0r** [comment]
Fixed in 3.1.2

**Comment by Horgul123** [comment]
Bestätigt :)
Läuft wieder! Danke für den schnellen Fix!

**Comment by klein0r** [comment]
Neuste Version von npm holen (nicht von GitHub!)

*Oder halt auf die Version im Beta-Repository warten - sollte morgen dann verfügbar sein*

<img width="1023" alt="Screenshot 2023-12-22 at 19 22 06" src="https://github.com/klein0r/ioBroker.trashschedule/assets/1959049/1dcdfdee-1bc0-4247-a463-6b78dec7dccb">
