### ISSUE TITLE
Leere Seite nach "Verwerfen"

### ISSUE THREAD

**Issue by Klaus-Lucas** [klein0r/ioBroker.trashschedule#209]
### The problem

Ich rufe den Adapter auf und lande bei der Registerkarte `Abfall-Typen`:
![klu_009](https://github.com/klein0r/ioBroker.trashschedule/assets/36620907/291486ab-aeba-4a1d-9e32-0f07757ff4bf)
Allein das Aufrufen, schaltet die Schaltflächen `Speichern` und `Speichern und Schliessen` frei, obwohl ich noch nichts geändert habe.

Ich wähle `Schliessen` und `Verwerfen`:
![klu_010](https://github.com/klein0r/ioBroker.trashschedule/assets/36620907/7f567b8c-98da-4cdf-a37c-85b39d3e1697)

Übersicht der Instanzen erscheint nicht mehr:
![klu_011](https://github.com/klein0r/ioBroker.trashschedule/assets/36620907/ad5f2953-f268-4a94-a4b1-e34410b8a191)

Wähle ich statt `Schliessen` die Registerkarte `Einstellungen` oder `ICAL-Einstellungen` und schließe dann den Adapter, so kommt erstmal der gleiche Fehler wie oben beschrieben. 
Rufe ich dann den Adapter erneut auf, so sind die Schaltflächen korrekt abgedunkelt:
![klu_012](https://github.com/klein0r/ioBroker.trashschedule/assets/36620907/5b2d589f-6288-44eb-9cbd-d769c3e66d78)
und ich kann den Adapter ohne den Verwerfen-Hinweis schließen und lande auch wieder auf der Instanz-Übersicht.

### Version of nodejs

18.19.0

### Version of ioBroker js-controller

5.0.17

### Version of Adapter

3.1.3

### Operating system running ioBroker

Ubuntu 22.04.3 LTS

**Comment by klein0r** [comment]
Da die Instanzeinstellungen und auch das Speichern der Änderungen usw. in der Hand des Admin-Adapters liegt, wäre die verwendet Admin-Version interessant.

**Comment by Klaus-Lucas** [comment]
jo, das hatte ich vergessen: `16.12.9` und jetzt neu auch `6.13.11.`
Neben dem oben beschrieben Verhalten in der Reg-Karte `Abfall-Typen` (Schaltflächen freigeschaltet)
ist mir aufgefallen, dass beim Verwerfen `http://<IP>:8081/index.html#` aufgerufen statt `http://<IP>:8081/index.html#tab-instances` aufgerufen wird, was zu der leeren Darstellung führt.

**Comment by klein0r** [comment]
Das müsste dann aber bei allen Adaptern so sein, welche jsonConfig verwenden.

**Comment by klein0r** [comment]
Admin bug, see https://github.com/ioBroker/ioBroker.admin/issues/2287

**Comment by Klaus-Lucas** [comment]
@klein0r 
Das eingangs beschriebene Verhalten auf der Abfall-Typen-Registerkarte ist so gewollt?
