### ISSUE TITLE
Adapter bleibt rot

### ISSUE THREAD

**Issue by Tagiwara** [klein0r/ioBroker.trashschedule#21]
Hallo, ich habe auf den JS-Controller 3.0.19 gewechselt und bekomme den Adapter nicht mehr grün. Vom Adapter ist die Version 0.0.5 installiert.
Die Instanz habe ich mal auf debug gestellt, leider wird überhaupt gar nix ins log geschrieben.

**Comment by capitaenz** [comment]
@Tagiwara Schon eine Lösung gefunden?
Ich musste mein System neu starten, da ich JavaScript per Blocky gekillt hatte und jetzt bleibt der Adapter auf gelb und schreibt auch nichts ins Log.
Habe JS 3.0.18
Hoffe @klein0r kann uns helfen oder sagen wie wir zur Lösung beitragen können.

**Comment by capitaenz** [comment]
@Tagiwara zumindest mein Problem ist gelöst und ich kann drüber schmunzeln.
Nach einem Neustart wurde die "Abfuhrtermin.ics" im Verzeichnis "tmp" gelöscht...
Nachdem ich diese dort erneut abgelegt habe und erst den ical-Adapter und dann den trashschedule-Adapter neu gestartet habe, wird der Adapter wieder grün.
Trotzdem danke an @klein0r und VG

**Comment by klein0r** [comment]
Gerade alles getestet mit den aktuellsten Versionen und keine Probleme. In den neuen Versionen wird das Debug-Log nochmal mit mehr Infos gefüllt.

Gelb = Keine Termine im iCal-Adapter gefunden. Dann liegt das Problem einen Schritt weiter vorn.
