### ISSUE TITLE
Feature Request: Weitere Müll "Organisationen"

### ISSUE THREAD

**Issue by tritanium73** [klein0r/ioBroker.trashschedule#210]
### The problem

Hallo Matthias,

wärst du so nett, wenn es deine Zeit zulässt, folgende "Müll" Online API Städte noch hinzuzufügen?

Ich habe die API derzeit via "blockly" angezapft, tue mich aber schwer mit einigen Berechnungen, die dein trashscheduler direkt als Objekte mitliefert.

Schau mal hier: MyMuell: (die hattest du ja bereits integriert)

```
https://mymuell.jumomind.com/mmapp/api.php?r=cities&city_id=&area_id=				-> Alle Städte
https://mymuell.jumomind.com/mmapp/api.php?r=streets&city_id=23911&area_id=		-> Alle Strassen einer cities ID
```

Im Homeassistant GIT hat jemand noch andere "Müll Dienstleister" einiger Kommunen ermöglicht. Unter anderem auch meine Stadt Recklinghausen.
Ich hatte mir dann das Py Script dort angesehen und daraus dann die http URLs der "Zusatzkommunen" abgeleitet.

-> hier der Link zum HA GIT: https://github.com/tuxuser/abfallapi_jumomind_ha/tree/master

Die API ist unter:        https://{services}.jumomind.com/mmapp/api.php    erreichbar

Folgende Services (Städte) würden dann noch mit ermöglicht werden:

SERVICES = {
    'ZAW': 'zaw',
    'Aurich': 'lka',
    'Altötting': 'aoe',
    #'Bad Homburg vdH': 'hom',
    'Lübbecke': 'lue',
    #'Hattersheim am Main': 'ham',
    'Barnim': 'bdg',
    'Minden': 'sbm',
    'Rhein-Hunsrück': 'rhe',
    'Recklinghausen': 'ksr',
    'Ingolstadt': 'ingol',
    'Uckermark': 'udg',
    #'Groß-Gerau': 'aws',
    'MyMuell': 'mymuell'
}

Für meine Stadt RECKLINGHAUSEN, die durch die "Kommunalen Service Betriebe Recklinghausen" mülltechnisch abgedeckt wird, lautet dann die URL:

```
https://ksr.jumomind.com/mmapp/api.php?r=streets&city_id=87&area_id=					-> Alle Strassen aus RE
https://ksr.jumomind.com/mmapp/api.php?r=trash&city_id=87&area_id=4520476				-> Neckarstraße AreaID 4520476
https://ksr.jumomind.com/mmapp/api.php?r=dates/0&city_id=87&area_id=4520476			-> Daten für Tonnen
https://ksr.jumomind.com/mmapp/api.php?r=calendar/2024-01&city_id=87&area_id=4520476	-> mit Datumsangabe JJJJ / MM
```

Wenn das klappen kann, würde ich liebend gerne wieder den trashscheduler verwenden :-)

lg Micha

### Version of nodejs

18.17.0

### Version of ioBroker js-controller

7.1.6

### Version of Adapter

3.1.3

### Operating system running ioBroker

ubuntu 22.04 "physisch"

### Checklist of files to include below

- [X] iobroker.current.log (Please share the logs in debug mode)
- [ ] Contents of the JavaScript browser console (always include in cases of issues with the user interface)

**Comment by ScumbagSteve** [comment]
Ich war die Tage auch in Kontakt mit den Entwicklern und wurde dabei ebenfalls auf diesen Link hingewiesen. Auch meine Stadt wäre dann dabei, daher guter Tipp 👍🏻

**Comment by klein0r** [comment]
Habe das Ganze hier schon vor längerer Zeit angefangen: https://github.com/klein0r/ioBroker.trashschedule/tree/abfall-io

**Comment by ScumbagSteve** [comment]
Sollen wir das Release dort testen?

**Comment by klein0r** [comment]
Ne, das läuft alles noch nicht richtig. Bei manchen Providern bekomme ich gar keine Städte zurück. Muss mir noch anschauen wie sich das zu mymüll unterscheidet.

**Comment by klein0r** [comment]
3.2.0

**Comment by tritanium73** [comment]
Du bist der Hammer :-D

-> Danke, gerade eben die 3.2.0 installiert, durchkonfiguriert mit "ksr" -> LÄUFT !
