### ISSUE TITLE
Nummerische Werte für Datum und Müllkategorie

### ISSUE THREAD

**Issue by Sp0b1e** [klein0r/ioBroker.trashschedule#224]
### I'm sure that

- [X] This issue is still present in the **current beta version** of this adapter
- [X] There is no other (open) issue with the same topic (use the search!)
- [X] This issue is not described in the adapter documentation / FAQ (read the docs!)

### Integration (ical, api, ...)

ical

### The problem

Zur einfacheren Verwendung der Werte in anderen System wäre es Hilfreich das Datum der einzelnen Müllabfuhr-Event in nummerischen Werten (value) für das Jahr (2024), den Monat (3) und den Tag (30) auszugeben. 
Vielleicht könnte man im gleichen Zug auch in den Datenpunkten für die nächste und übernächste Abholung nummerische Werte für den Mülltypen definieren (z.B. typ=bio, typNum = 1). 

### Version of nodejs

18.18.2

### Version of ioBroker js-controller

5.0.12

### Version of adapter

v3.2.0

**Comment by klein0r** [comment]
Das wäre technisch erstmal kein Problem, aber warum ist das notwendig? Wie werden die Werte in Loxone dargestellt und warum reicht der Datenpunkt mit dem formatierten Datum aktuell nicht aus?

**Comment by klein0r** [comment]
No response ...
