### ISSUE TITLE
[Bug]: Hirse in der VIS

### ISSUE THREAD

**Issue by mcm1957** [klein0r/ioBroker.trashschedule#226]
### I'm sure that

- [X] This issue is still present in the **current beta version** of this adapter
- [X] There is no other (open) issue with the same topic (use the search!)
- [X] This issue is not described in the adapter documentation / FAQ (read the docs!)

### Integration (ical, api, ...)

n/a

### The problem

Da hat der Translator bei deutsch ganze Arbeit geleistet :-)

```
        "hide": {
            "en": "Hide",
            "de": "Hirse",
            "ru": "Скрыть",
            "pt": "Esconde-te",
            "nl": "Verberg je",
            "fr": "C'est ça",
            "it": "Nascondi",
            "es": "Escóndete",
            "pl": "Hide",
            "uk": "Приват",
            "zh-cn": "导 言"
        },
```
https://github.com/klein0r/ioBroker.trashschedule/blob/4579d79724d22d418039891728ae7132c11b9612/widgets/trashschedule/js/trashschedule.js#L132

### Version of nodejs

n/a

### Version of ioBroker js-controller

n/a

### Version of adapter

3.2.0

**Comment by klein0r** [comment]
😄 nice one
