### ISSUE TITLE
[Bug]: AbfallPlus wird nur ein Ort angezeigt

### ISSUE THREAD

**Issue by bambi-arch** [klein0r/ioBroker.trashschedule#229]
### I'm sure that

- [X] This issue is still present in the **current beta version** of this adapter
- [X] There is no other (open) issue with the same topic (use the search!)
- [X] This issue is not described in the adapter documentation / FAQ (read the docs!)

### Integration (ical, api, ...)

Webservice

### The problem

Hallo Matthias, ich wollte von ical auf Abfallplus wechseln. Nach der Auswahl wird mir jedoch nur ein Ort angezeigt. Wenn ich z.B. Traunstein eingebe, wird dieser nicht gefunden. Auf der Internetseite von Abfall+ wird dieser jedoch als unterstützt angezeigt.

![Bildschirmfoto 2024-05-25 um 11 51 53](https://github.com/klein0r/ioBroker.trashschedule/assets/104907692/d631677e-6dd9-4b10-8f4e-9748b8645aa1)
![Bildschirmfoto 2024-05-25 um 11 52 48](https://github.com/klein0r/ioBroker.trashschedule/assets/104907692/4e351c03-ebbe-4604-b66c-0b4bd7ef1ec3)
![Bildschirmfoto 2024-05-25 um 11 52 57](https://github.com/klein0r/ioBroker.trashschedule/assets/104907692/06d342b1-873d-428b-b394-8447e33404f7)

### Version of nodejs

18.17.1

### Version of ioBroker js-controller

 5.0.19

### Version of adapter

3.30

**Comment by bambi-arch** [comment]
Ich bekomme nach Neustart des Adapters im Protokoll vom Admin-Adapter folgende Fehlermeldung:
trashschedule has an invalid jsonConfig: [{"instancePath":"/items/_advanced/items/trashtypes/items/4","schemaPath":"#/items/allOf/5/then/allOf/1/additionalProperties","keyword":"additionalProperties","params":{"additionalProperty":"width"},"message":"must NOT have additional properties"},{"instancePath":"/items/_advanced/items/trashtypes","schemaPath":"#/patternProperties/%5E.%2B/allOf/23/if","keyword":"if","params":{"failingKeyword":"then"},"message":"must match \"then\" schema"},{"instancePath":"/items/_advanced","schemaPath":"#/properties/items/patternProperties/%5E.%2B/allOf/8/if","keyword":"if","params":{"failingKeyword":"then"},"message":"must match \"then\" schema"},{"instancePath":"","schemaPath":"#/if","keyword":"if","params":{"failingKeyword":"then"},"message":"must match \"then\" schema"}]

**Comment by klein0r** [comment]
> Nach der Auswahl wird mir jedoch nur ein Ort angezeigt.

Ja, weil ich die Adressen / Schlüssel der anderen Orte nicht kenne.

**Comment by bambi-arch** [comment]
Muss ich den Schlüssel bei AbfallPlus erfragen oder wie komme ich an den ran?

**Comment by klein0r** [comment]
Den habe ich aus einem Widget ausgelesen. Du musst eigentlich nichts eintragen. Für die hinterlegten Orte (aktuell nur der eine) sollte das alles so funktionieren.

**Comment by klein0r** [comment]
Habe keine weiteren API Keys
