### ISSUE TITLE
NextAfter ist gleich Next

### ISSUE THREAD

**Issue by FRYYYYYY** [klein0r/ioBroker.trashschedule#26]
Ich habe heute bei meinen Abfragen festgestellt, dass die Werte in Next und NextAfter mit dem selben Tag gefüllt sind. Somit funktioniert die Einstellung "Aktuellen Tag ab Stunde X überspringen" nicht, da der nächste Tag immer noch mit dem selben Tage gefüllt ist:

![image](https://user-images.githubusercontent.com/13643787/82061642-46e18880-96c9-11ea-8840-ff73e6e1bf82.png)

**Comment by Feuer-sturm** [comment]
Das Verhalten konnte ich gerade bei mir in der Version 0.0.7 und jetzt mit der 0.0.8 nicht beobachten. Welche Version setzt du ein?

Stimmen die Einträge im Kalender? Was gibt der ical Adapter im Datenpunkt ical.x.data.html aus? 

Hab gerade mal 2 Testeinträge gemacht für eine Leerung heute und eine Leerung für morgen.
Wenn ich bei "Aktuellen Tag ab Stunde X überspringen" jetzt 22 eintrage, dann wird mir die morgige Leerung und die darauffolgende Leerung angezeigt.
Wenn ich bei "Aktuellen Tag ab Stunde X überspringen" 23 eintrag, dann wird mir die heutige und die morgige Leerung angezeigt.
Sieht erstmal i.O. aus.

**Comment by FRYYYYYY** [comment]
Ich nutze die Version 0.0.8.

Kann gerade nur Screenshots vom Handy anhängen, sonst schaff ich das heute nicht mehr :-)

Hier sieht man, dass iCal für den Tag 0 (Heute) Events hat, für 1 (Morgen) aber nicht:
![454D4D1C-ED22-438F-BF37-5BD2C83BCE87](https://user-images.githubusercontent.com/13643787/82095470-58de1e00-96ff-11ea-988d-d140a6741182.jpeg)
 
Trashschedule zeigt mir bei Next und NextAfter den selben Wert an; als Idee/Beispiel ganz unten sieht man bei Wertstoff, dass es kein nextdate gibt:

![432CC188-EAC0-4D92-A7C4-580B288EDB6F](https://user-images.githubusercontent.com/13643787/82095598-a3f83100-96ff-11ea-90be-0f694c2c069a.jpeg)

Vielleicht wird NextAfter nicht geleert...?

**Comment by Feuer-sturm** [comment]
Meine ical Instanz ist wie folgt konfiguriert:
![grafik](https://user-images.githubusercontent.com/25422320/82096810-f6d2e800-9701-11ea-93d7-cd8626db4b74.png)

Bei den Events / Ereignissen ist gar nichts eingetragen
![grafik](https://user-images.githubusercontent.com/25422320/82096876-123df300-9702-11ea-9c57-ca2038ed1379.png)

Die Events sind dementsprechend auch nicht gefüllt bei den Objekten. Hast du hier was eingetragen?
![grafik](https://user-images.githubusercontent.com/25422320/82097169-ab6d0980-9702-11ea-96c5-a4cd0e0907f6.png)


Trashschedule Instanz:
![grafik](https://user-images.githubusercontent.com/25422320/82096942-339edf00-9702-11ea-9f67-2a801fc6b003.png)

![grafik](https://user-images.githubusercontent.com/25422320/82096919-297ce080-9702-11ea-8b26-45e94480e51b.png)

Aufbau im Kalender:
![grafik](https://user-images.githubusercontent.com/25422320/82097010-54ffcb00-9702-11ea-946d-673d8674e65e.png)

**Comment by FRYYYYYY** [comment]
Ich hatte bei iCal etwas eingetragen:
![32C463DC-F072-4005-824F-EA0C604E140D](https://user-images.githubusercontent.com/13643787/82097989-5500ca80-9704-11ea-882f-93192768f416.jpeg)

Und jetzt mal gelöscht:
![1866E55D-F0F4-4AB5-84EE-E27AEC1F961A](https://user-images.githubusercontent.com/13643787/82098004-5e8a3280-9704-11ea-8ce3-42a841235d78.jpeg)

Adapter iCal und Trashschedule Neugestalten, aber NextAfter ist immer noch gefüllt:

![39E2EF87-A468-4012-8640-BD4C34F0C27B](https://user-images.githubusercontent.com/13643787/82098038-706bd580-9704-11ea-9f8e-74ced91c397c.jpeg)

Der Timestamp sagt, dass die Änderung noch von heute Nacht ist und gar nicht geändert wurde:
![DAC7400A-033B-4721-A70E-A1E1F5813058](https://user-images.githubusercontent.com/13643787/82098243-dbb5a780-9704-11ea-8f7c-8f2bdab1d635.jpeg)


Der Trashschedule Log sagt aber komischer Weise, dass es keine Events gibt:
![9EE330B9-1F18-4AAA-9C73-E74551EB2894](https://user-images.githubusercontent.com/13643787/82098134-a1e4a100-9704-11ea-9c0c-e307c2733e83.jpeg)

**Comment by Feuer-sturm** [comment]
Hast du mal deinen Browser Cache komplett geleert und die Admin seite neu geladen?

**Comment by FRYYYYYY** [comment]
Ja... die Werte stehen im Objekt. Liegt nicht am Browser. Per Telegram frage ich die Werte ab, daher ist es mir auch erst aufgefallen, dass die Werte nicht geleert werden und mir Telegram auf meine Statusabfrage hin jetzt noch meldet, dass ein Müllevent morgen stattfindet, obwohl keins ist. 

Anderer Browser:
![EE6BF175-C6FC-4A7D-AC8F-8684675855D4](https://user-images.githubusercontent.com/13643787/82099148-db1e1080-9706-11ea-8805-cbe90c726053.jpeg)

Ich vermute, dass das löschen der Werte aus dem Objekt nicht funktioniert.

**Comment by Feuer-sturm** [comment]
Bei mir werden die Objekte unter NextAfter aktualisiert. Es scheint somit kein generelles Problem zu sein.

Welche Zahl ist bei dir in der Tagesvorschau im ical.0 bei den Haupteinstellungen eingetragen?

Wie sieht der Inhalt von diesem Datenpunkt aus:
![grafik](https://user-images.githubusercontent.com/25422320/82099663-2dabfc80-9708-11ea-97f3-57117d17e144.png)

**Comment by FRYYYYYY** [comment]
> Welche Zahl ist bei dir in der Tagesvorschau im ical.0 bei den Haupteinstellungen eingetragen?
-> 7
> Wie sieht der Inhalt von diesem Datenpunkt aus:
`<span style="font-weight: bold; color: white"><span class="icalNormal iCal-AWG_Abfallkalender 2020">In einer Woche  </span></span><span style="font-weight: normal; color:white"><span class='icalNormal2 iCal-AWG_Abfallkalender 20202'> Bio/ !!! Terminverschiebung !!!</span></span>`

Next ist heute aktualisiert, NextAfter ist jetzt aber gestern:
![F96C91AD-196C-4774-BD5F-D1A2D059EEF9](https://user-images.githubusercontent.com/13643787/82114044-8b693480-975a-11ea-91c8-f8e75214601f.jpeg)

Ändere ich den „Forecast“ auf 28 Tage, dann stimmt NextAfter jetzt:
![Uploading EAF42C4E-19DE-4558-BC53-930845979D17.jpeg…]()

**Comment by Feuer-sturm** [comment]
Danke für die Rückmeldung, dass es funktioniert :-)

**Comment by klein0r** [comment]
NextAfter wird logischerweise nicht aktualisiert, wenn man so weit nicht in die Zukunft schauen kann. Da muss ich mir noch etwas überlegen. Also angenommen der nächste Termin ist kurz vor der eingestellten Grenze im iCal-Adapter, dann wird nextAfter nie gefunden, weil ja danach nichts mehr abgerufen wird.

Eventuell trenne ich mich in zukünftigen Versionen auch komplett von der iCal-Abhängigkeit. Das macht scheinbar nur Probleme...
