### ISSUE TITLE
not all trash bins are shown in vis

### ISSUE THREAD

**Issue by SchiFrank** [klein0r/ioBroker.trashschedule#28]
**Describe the bug**  
I have defined 4 trash bins, but in vis only 2 are displayed, although the json object includes all 4 trash bins.

**Versions:**  
trashschedule 0.0.9
Platform: linux
os: linux
Architecture: x64
CPUs: 4
Speed: 479 MHz
Model: Intel(R) Celeron(R) CPU  N3150  @ 1.60GHz
RAM: 3.7 GB 
System uptime: 16:48:00
Node.js: v10.20.1
NPM: 6.14.4
adapters count: 350
Disk size: 54.1 GiB
Disk free: 44.7 GiB
Uptime: 16:47:55
Active instances: 28

![trashschedule_vis](https://user-images.githubusercontent.com/50178591/83321427-ec5f3500-a24f-11ea-8ddc-8a5c3d9c1080.PNG)
![Trashschedule1](https://user-images.githubusercontent.com/50178591/83321428-ecf7cb80-a24f-11ea-8c45-8374008c39e1.PNG)
![Trashschedule2](https://user-images.githubusercontent.com/50178591/83321429-ed906200-a24f-11ea-9742-0dbec1c2be13.PNG)
![trash schedule 3](https://user-images.githubusercontent.com/50178591/83321431-ee28f880-a24f-11ea-8063-779085b38d56.jpg)
[trashbin_logfile.txt](https://github.com/klein0r/ioBroker.trashschedule/files/4705193/trashbin_logfile.txt)

**Comment by klein0r** [comment]
Please post the console log of the browser output. In VIS runtime, just use Chrome, Safari, Firefox or any other browser with integrated developer tools to check for possible errors.

1. Right click anywhere and click "inspect" (Element untersuchen in German)

![Screenshot 2020-05-30 at 10 20 32](https://user-images.githubusercontent.com/1959049/83323493-5af7bf00-a25f-11ea-9fbf-b760ac2b0fcb.png)

2. Navigate to "Console" Tab (Konsole)
3. Reload the Page without using the cache (Ctrl+Shift+R)
4. Check the console tab and post the errors (if present)

**Before** you do that:

1. enable the expert mode in the adapters tab
2. Search for "VIS" and click the "upload" button
3. Search for "Trashschedule" and click the "upload" button

![Screenshot 2020-05-30 at 10 24 51](https://user-images.githubusercontent.com/1959049/83323540-d0fc2600-a25f-11ea-9e2a-c8d8f09a38c3.png)

**Comment by SchiFrank** [comment]
After I uploaded VIS and Trashschedule the problem was solved. I attached the console file 
for before I uploaded vis and trash schedule, so you can analyze the problem, if you want.
![trash schedule console](https://user-images.githubusercontent.com/50178591/83327181-4b39a400-a27a-11ea-9ad9-9f12e4ddee72.PNG)

[trash schedule console.txt](https://github.com/klein0r/ioBroker.trashschedule/files/4705554/trash.schedule.console.txt)

**Comment by SchiFrank** [comment]
Danke Matthias :-)

Am Sa., 30. Mai 2020 um 10:25 Uhr schrieb Matthias Kleine <
notifications@github.com>:
