### ISSUE TITLE
Fehler im BIld

### ISSUE THREAD

**Issue by totocotonio** [klein0r/ioBroker.trashschedule#29]
Hi,
bei mir wird das Widget nur mit 2 Tonnen angezeigt, GELB und SCHWARZ
Die grüne Tonne fehlt.

Im Json werden aber aller 3 Termine angezeigt.

**Comment by zoxxy2000** [comment]
Bei mir wird auch nur eine Tonne im Widget angezeigt. 
Wenn ich die Tabelle nehme, stehen dort allerdings alle drin.

**Comment by klein0r** [comment]
Diese Punkte bereits berücksichtigt? https://github.com/klein0r/ioBroker.trashschedule/blob/master/faq_de.md

**Comment by totocotonio** [comment]
alle punkte berücksichtigt, jetzt nochmal über die Katze auf 0.0.9 und einen upload gemacht.
Farbe der tonnen sind alle grau
![trash](https://user-images.githubusercontent.com/48123111/84572683-05adc880-ad9c-11ea-8aa0-6fa70a390fec.PNG)

**Comment by klein0r** [comment]
Bitte nie über die "Katze" einen Adapter installieren. Das sind Entwicklungsstände. Über die Katze kommt man nie auf eine genaue Version - Du kannst also nicht über die Katze 0.0.9 installiert haben. Das ist technisch nicht möglich.

https://www.youtube.com/watch?v=rPR_QRGhAzM
