### ISSUE TITLE
Ungenaue Berechnung / Rundung days left

### ISSUE THREAD

**Issue by 5G7K** [klein0r/ioBroker.trashschedule#3]
ICal Eintrag in 90 Tagen
100 Tage werden im ICal im voraus angezeigt
Days Left wird berechnet auf 89.958333333333

![grafik](https://user-images.githubusercontent.com/60315312/73134644-49947100-4039-11ea-9aaa-e8da3ba74f48.png)

Wäre super wenn das behoben werden könnte. Danke!

**Comment by klein0r** [comment]
Ich könnte mir vorstellen, dass der Termin so weit in die Zukunft gerückt ist, dass die Zeitumstellung am 29. März mit eingerechnet wird. Zumindest kann ich das nur für Termine nachstellen, welche über die Uhrzeitumstellung hinweg gehen. Dadurch sind es ja nicht mehr genau 90 Tage, sondern eben eine Stunde weniger. Korrigiere ich in der nächsten Version!
