### ISSUE TITLE
Farben der Tonnen

### ISSUE THREAD

**Issue by totocotonio** [klein0r/ioBroker.trashschedule#30]
alle punkte berücksichtigt, jetzt nochmal über die Katze auf 0.0.9 und einen upload gemacht.
Farbe der tonnen sind alle grau
![trash](https://user-images.githubusercontent.com/48123111/84572737-5fae8e00-ad9c-11ea-9607-9af91a13ad29.PNG)

**Comment by klein0r** [comment]
Wenn der Adapter über die Katze installiert wurde, hast Du einen Entwicklungsstand installiert. Dafür kann ich keinen Support bieten, da es sich um keine freigegebene Version handelt.
