### ISSUE TITLE
tonnen immer noch grau

### ISSUE THREAD

**Issue by totocotonio** [klein0r/ioBroker.trashschedule#31]
So, 
alles deinstalliert und bereinigt.

Alles neu inst. und die tonnen sind immer noch grau.

Gibt es noch eine Lösung für mich.

**Comment by klein0r** [comment]
Welche Farben hast Du denn konfiguriert?

**Comment by totocotonio** [comment]
Hi,
ich habe den IObroker nochmal kompl aufgesetzt!

Jetzt geht der Adapter wieder.

Danke für deine Hilfe.
