### ISSUE TITLE
Termine werden nicht gefunden

### ISSUE THREAD

**Issue by ChristianGrieger** [klein0r/ioBroker.trashschedule#32]
Hallo zusammen,

ich habe leider ein leichtes Problem mit dem Adapter.

Ich habe einen Kalender angelegt, den bei Google hinterlegt und dann wie beschrieben den ICal-Adapter installiert und eingebunden. Danach habe ich den Kalender in diesem Plugin ausgewählt.

Leider werden keine Termine für "Schadstoffe" und "Metallschrott" gefunden. Die Termine sind definitiv vorhanden. Ich habe nun mehrfach beide Adapter gelöscht, die Termine umbenannt, weil ich dachte das es am Namen liegen könnte und und und...

<img width="958" alt="Bildschirmfoto 2020-06-16 um 09 20 22" src="https://user-images.githubusercontent.com/8712219/84744197-36b41600-afb3-11ea-9424-f7cb1a46b238.png">
<img width="810" alt="Bildschirmfoto 2020-06-16 um 09 20 14" src="https://user-images.githubusercontent.com/8712219/84744206-387dd980-afb3-11ea-8242-229eed18491b.png">
<img width="1609" alt="Bildschirmfoto 2020-06-16 um 09 20 09" src="https://user-images.githubusercontent.com/8712219/84744214-3b78ca00-afb3-11ea-9a7c-f5d91e7ad4ba.png">
<img width="803" alt="Bildschirmfoto 2020-06-16 um 09 20 01" src="https://user-images.githubusercontent.com/8712219/84744228-3e73ba80-afb3-11ea-90a5-c913ab47126f.png">

**Comment by klein0r** [comment]
Die Punkte aus den FAQ kannst Du auf jeden Fall ausschließen?
https://github.com/klein0r/ioBroker.trashschedule/blob/master/faq_de.md

**Comment by ChristianGrieger** [comment]
Ich hatte die 30 Tage aus dem Video übernommen :) Mit 58 scheint es zu gehen. Vielen Dank.
