### ISSUE TITLE
2 Müllarten am gleichen Tag aber unterschiedlich viele Tage "left"

### ISSUE THREAD

**Issue by Finki007** [klein0r/ioBroker.trashschedule#35]
**Describe the bug**  
Bio und Restmüll kommen am gleichen Tag aber der daysleft Wert ist unterschiedlich:
![image](https://user-images.githubusercontent.com/11229398/89804736-de257300-db34-11ea-8f7a-02aef3a75a04.png)

**Comment by klein0r** [comment]
So kann ich leider nicht helfen - was ich brauche:

- iCal Adapter Version
- iCal Adapter Einstellungen
- iCal Datei / Zugriff auf den Kalender
- Trashschedule Adapter Version
- Trashschedule Adapter Einstellungen

**Comment by Finki007** [comment]
@klein0r okay kein Thema hier sind die Angaben:

iCal Adapter Version: 1.7.0
iCal Adapter Einstellungen: 
![image](https://user-images.githubusercontent.com/11229398/89872236-f5a63f80-dbb8-11ea-8168-bf5665cc8395.png)

iCal Datei / Zugriff auf den Kalender: 
[Leerungstermine345103.txt](https://github.com/klein0r/ioBroker.trashschedule/files/5055550/Leerungstermine345103.txt)
ist eine ics Datei nur für den Upload auf txt geändert

Trashschedule Adapter Version: 0.0.10
Trashschedule Adapter Einstellungen:
Allgemein:
![image](https://user-images.githubusercontent.com/11229398/89872296-0656b580-dbb9-11ea-81e9-ede42ec6640e.png)
Abfalltypen:
![image](https://user-images.githubusercontent.com/11229398/89872355-1a9ab280-dbb9-11ea-9aac-ff72cc66bf0e.png)

**Comment by klein0r** [comment]
In der Datei finde ich keine Termine, welche so heißen wie deine "Gilt für Termine" Spalte. Überall steht "in Schorndorf", aber das ist in keinem Termin enthalten.

`cat Leerungstermine345103.ics | grep "in Schorndorf"`

**Comment by klein0r** [comment]
NextAfter wird bei mir stand heute gar nicht aktualisiert, weil der iCal-Adapter ja auch nur 7 Tage in die Zukunft Daten holt (siehe iCal Konfiguration). Den Wert würde ich auf jeden Fall höher stellen. Auf 30 Tage o.ä. - sodass mindestens 2 Termine von jeder Abholung in dem Bereich liegen.

**Comment by klein0r** [comment]
Ansonsten siehe auch: https://github.com/klein0r/ioBroker.trashschedule/blob/master/faq_de.md

**Comment by Finki007** [comment]
@klein0r okay ich werde die Einstellung in ical auf jeden Fall erhöhen.
Hier nochmal die richtige Datei:
[abfall.txt](https://github.com/klein0r/ioBroker.trashschedule/files/5055672/abfall.txt)

**Comment by Finki007** [comment]
@klein0r okay aber ich denke das es mit der iCal Einstellung jetzt behoben wurde. Danke dir für den coolen Adapter und den guten Support ;)

**Comment by klein0r** [comment]
Ich baue mal noch mehr Fehlermeldungen ein, damit einem das direkt um die Ohren fliegt und ich nicht eine Stunde nach Konfigurationsfehlern suche 😄
