### ISSUE TITLE
CSS bug if date is too long (VIS)

### ISSUE THREAD

**Issue by klein0r** [klein0r/ioBroker.trashschedule#37]
![120291731_4562222863849820_7259660656363535234_n](https://user-images.githubusercontent.com/1959049/94657802-49542000-0302-11eb-8a2e-e26e4b835ee7.jpg)

**Comment by Mazze85** [comment]
i have the same Problem, any fix vor that ?

**Comment by klein0r** [comment]
@Mazze85 Since this issue is still open, nope. Feel free to create a pull request.

**Comment by klein0r** [comment]
Fixed in 1.0.0
