### ISSUE TITLE
trashschedule.0.next.date Should be a date object, not string

### ISSUE THREAD

**Issue by ahnungsbefreit** [klein0r/ioBroker.trashschedule#38]
**Describe the bug**  
The format of the objects "next.date" and "nextAfter.date" is string, not date (with EPOCH time). This is making the further processing of this information unnecessarily complicated.

**To Reproduce**  
1. Set up trashschedule adapter
2. Check objects created

**Expected behavior**  
The objects "next.date" and "nextAfter.date" should be of type date (with EPOCH time). For users requiring strings, the "dateFormat" is already provided.

**Screenshots & Logfiles**  
{
  "from": "system.host.ioBroker-pi.cli",
  "ts": 1601640887401,
  "common": {
    "name": "Next date",
    "type": "string",
    "role": "date.start",
    "read": true,
    "write": false
  },
  "native": {},
  "acl": {
    "object": 1636,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator",
    "state": 1636
  },
  "_id": "trashschedule.0.next.date",
  "type": "state"
}

**Versions:**  
 - Adapter version: 0.0.11
 - JS-Controller version: 3.1.6
 - Node version: <node-version>v12.18.4
 - Operating system: Linux

**Comment by klein0r** [comment]
Date is not allowed as a type

**Comment by DutchmanNL** [comment]
> Date is not allowed as a type

It is, epoch time weich is mich waaier robuste im Scripts to work Sith than a String 

See iobroker Doku : 

date (common.type = string - parsable by "new Date(ddd)" string
date (common.type = number - epoch seconds * 1000

https://github.com/ioBroker/ioBroker/blob/master/doc/STATE_ROLES.md

**Comment by klein0r** [comment]
@DutchmanNL But date is not listed here (allowedObjectTypes, allowedStateTypes):

https://github.com/ioBroker/ioBroker.js-controller/blob/bdc400408352edfa4d3b2b260477171f7a001d4a/lib/tools.js#L2113-L2137

How looks a correct configuration? Like this?

```
        {
            "_id": "next.date",
            "type": "date",
            "common": {
                "name": "Next date",
                "type": "string", // string vs. number?
                "role": "date.start",
                "read": true,
                "write": false
            },
            "native": {}
        }
```

**Comment by DutchmanNL** [comment]
Please use the epoch time here as number as indicated in State role Definition and role Date.

The Admin will Translate epoch time automatically to a date String im Admin, but for scripts you want the epoch time and Not a String as than you Need to convert this String to epoch anyway

**Comment by klein0r** [comment]
And why is type = date not defined in the array of allowedObjectTypes (see link)? I'm a bit confused.

**Comment by Jey-Cee** [comment]
As you can see here there is no Object type 'date'
![image](https://user-images.githubusercontent.com/16007760/98353267-5eb61b80-201f-11eb-9a7d-216ec6386724.png)
Also there is no common.type 'date'.
Only in the roles we have 'date'.
![image](https://user-images.githubusercontent.com/16007760/98353663-e8fe7f80-201f-11eb-87f0-5b4db91155f9.png)

The difference in handling is explained by @DutchmanNL, so it is better to use common.type 'number'. But the actual setting is also OK according to documentation.

**Comment by klein0r** [comment]
I'm totally confused now 😄 
So there is no explicit definition of type date - and I should use string or number to store a date (as implemented right now)?

The documentation is a bit weird an not clear.

**Comment by Jey-Cee** [comment]
The documetation is absolutley clear, but the terms thrown in this discussion are incorrect.

There is a definition for date, but JS-controller and JS does not know an object type date. 
The type defines an ioBroker Object, common.type defines the JS object. 
Read [here](https://wiki.selfhtml.org/wiki/JavaScript/Datentyp) for JS datatypes (German)
and [here](https://www.iobroker.net/#de/documentation/dev/objectsschema.md?objekttypen) for ioBroker object types.

So the definition for date in ioBroker context is the role and the JS datatype. Yes it is not explicit, for now.

**Comment by klein0r** [comment]
> So the definition for date in ioBroker context is the role and the JS datatype. Yes it is not explicit, for now.

Got it. But I still don't understand the initial request / the issue.
If the JavaScript type is string, my date object will be casted into a string before it will be stored.

> **Describe the bug**
> The format of the objects "next.date" and "nextAfter.date" is string, not date (with EPOCH time).

Of course it is - as the documentation recommends. So I've closed the issue because I have no idea how to change that behaviour with the default JS data types.

**Comment by DutchmanNL** [comment]
> I could change the type to number and store epoch time like
> `const secondsSinceEpoch = Math.round(date.getTime() / 1000)`
> 
> **Or what is best practice?**

exactly :) as the issue describes from beginning we would like to just have the Unix time Stamp (Epoch time) in it so it can be easier used for scripting and all other kind of fancy stuff :)

Making calculation with a string is .... so please change to number and propper Unix time format Javascript understand and can work with natively :)

**Comment by ahnungsbefreit** [comment]
> Making calculation with a string is .... so please change to number and propper Unix time format Javascript understand and can work with natively :)

That was exactly my point...
