### ISSUE TITLE
Error in logs where there should be no error (cosmetic stuff maybe)

### ISSUE THREAD

**Issue by mediaDS** [klein0r/ioBroker.trashschedule#40]
**Describe the bug**  
I get red **error** messages like this in the logs:

`trashschedule.0 | 2020-11-05 11:30:12.931 | error | (17132) nextAfter has no entries. Check configuration of iCal and trashschedule!
`
I assume this should not generate an error - it is just that there are no more entries. Maybe a warning but definately not an error.

**Expected behavior**  
If there are no more entries it should give a  warning at most.

**Versions:**  
 - Adapter version: 4.9.7
 - JS-Controller version: 3.1.6
 - Node version:  12.19.0
 - Operating system: Linux Arm64

**Comment by klein0r** [comment]
@mediaDS I've added this error because I've received a lot of questions why there are no entries in nextAfter. But you're right, I'll change it to a warning.

**Comment by mediaDS** [comment]
Thanks so much for the prompt reaction! Looking forward to the next update :)

**Comment by mediaDS** [comment]
Updated to 1.0.0 today - still red error messages. The adapter is now yellow in the instance list. Next trash date is eleven days from now and there is no nextafter for 14 days. Should be no error and no warning either - this schedule is normal to have no nextafter for a while. Sometimes the gap between schedules is 4 weeks. Just an info message would suffice I guess.



```
trashschedule.0 | 2020-11-06 20:51:58.285 | error | (10854) no events found in iCal instance - check configuration and restart adapter
-- | -- | -- | --
```

**Comment by mediaDS** [comment]
Arrg, now the adpater isn't working at all. All objeccts are empty (see screenshots). I unisntalled all and re-installe dit again - the same. ical.0 is running properly with the latest ical schedule. Let me know if I could help you with more information.

![Bildschirmfoto vom 2020-11-06 21-15-35](https://user-images.githubusercontent.com/48488629/98411784-fbf06e80-2076-11eb-96f7-149df6e4dfe6.png)

**Comment by klein0r** [comment]
@mediaDS Trashschedule cannot find any iCal events. This means, your iCal configuration is wrong or you have filtered all events in the iCal instance.

**Comment by mediaDS** [comment]
Hello,
you are absolutely right - I digged a bit deeper and found that iCal has no further schedules. Sorry, it is not your adapter, it is iCal. And yes, there are schedules in the iCal calender but iCal cannot find them for unknown reasons. Anyway, thanks for the help and have fun :)

**Comment by klein0r** [comment]
I'm working on an ical pull request to display dates of the past

**Comment by mediaDS** [comment]
Moin,
I've installed all the latest updates (iCal 1.74 & Trashschedule 1.0.1) and everything is working fine now. Thanks so much :)

Have a nice weekend.

Dieter
