### ISSUE TITLE
Invalid Date at VIS Widget - 1.0.0

### ISSUE THREAD

**Issue by skvarel** [klein0r/ioBroker.trashschedule#41]
Seit dem Update auf 1.0.0 habe ich kein Datum mehr im Widget. Wo muss ich da was ändern bzw. anpassen?

Gruß, Sven.

![grafik](https://user-images.githubusercontent.com/1114419/98377354-fed26b80-2044-11eb-860f-548ada909b06.png)

![grafik](https://user-images.githubusercontent.com/1114419/98377471-21fd1b00-2045-11eb-9285-4e8881c82fea.png)

**Comment by klein0r** [comment]
Upload auf Trashschedule und VIS machen. JavaScript hat sich geändert.

**Comment by skvarel** [comment]
Leider keine Besserung. Es bleibt bei 'Invalid Date'

**Comment by skvarel** [comment]
> 
> 
> Upload auf Trashschedule und VIS machen. JavaScript hat sich geändert.

Leider keine Besserung. Es bleibt bei 'Invalid Date'

**Comment by klein0r** [comment]
In welcher Reihenfolge hast du den Upload auf den Adaptern ausgeführt?

**Comment by skvarel** [comment]
> 
> 
> In welcher Reihenfolge hast du den Upload auf den Adaptern ausgeführt?

So, wie Du es geschrieben hast. Erst Trash dann VIS

**Comment by klein0r** [comment]
Browsercache geleert? Eventuell lädt er trotzdem noch die alte JS-Datei

**Comment by AnkhMorpork78** [comment]
Hab mich auch an deine Anleitung gehalten, aber bei mir wird garnichts angezeigt.
Egal ob Chrome, Firefox, Edge, Opera, Chromium, usw....

**Comment by klein0r** [comment]
Dann bitte erstmal weiterhin die Version aus stable nutzen.
Bei anderen hat ein Upload der beiden Adapter die Lösung gebracht.

**Comment by AnkhMorpork78** [comment]
Waaahhh.

Ich nehm alles zurück und behaupte das Gegenteil.
hab erst den Trash und dann die Vis geuploadet.

Das hat nix gebracht
Dann hab ich einfach mal den ioBroker neugestartet und siehe da, jetzt klappt es.

Danke für deine Mühen und super Adapter. 😉

**Comment by klein0r** [comment]
Am besten direkt auf 1.0.1 gehen. War noch ein Fehler drin der Teilweise das falsche Datum anzeigen könnte.

**Comment by AnkhMorpork78** [comment]
Hab ich gemacht.

Er zeigt zwar das falsche Datum an, aber das war beim alten auch. Sollte sich ja über Nacht wieder einrenken.

(Ist OT für das Issue)

**Comment by klein0r** [comment]
Sonst beide Instanzen einmal neustarten (ical und trashschedule), dann wird alles neu berechnet

**Comment by AnkhMorpork78** [comment]
Leider gibt es immer noch Probleme.

In den Objecten bei IOBroker werden die richtigen Tage angezeigt. (Mon Nov 09 2020...)
In der Vis wird mir aber Sontag, 8.11 angezeigt. Selbst Neustart, und sonstiges half nichts.

**Comment by klein0r** [comment]
Bitte neuen Issue mit komplettem Debug Log erstellen
