### ISSUE TITLE
bei Verwendung von Offset keine korrekte Berechnung/Anzeige der Rest-Tage

### ISSUE THREAD

**Issue by sly-1** [klein0r/ioBroker.trashschedule#42]
Ich habe die Stable Version 1.0.0 installiert. 
Seitdem ist die Anzeige der Rest-Tage im Widget nicht mehr korrekt. 

Abholung der **Biotonne** war heute (**6**.11.2020.) 

**Konfiguration der Instanz (ohne Offset):** 
![image](https://user-images.githubusercontent.com/59330827/98401838-98f6db80-2066-11eb-9d8c-778a40affbc0.png)

**Daraus resultiert diese Anzeige:**
![image](https://user-images.githubusercontent.com/59330827/98402602-df006f00-2067-11eb-8711-5098e92cc8d7.png)

Die heutige Abholung der Biotonne wird übersprungen. Das soll auch so ab 12:00 sein. 
Ich benötige aber einen Offset von +1. 
Wenn ich den Offset konfiguriere, dann stimmt die Datumsangabe im Widget, aber die heutige Abholung der Biotonne wird nicht mehr übersprungen.

**Konfiguration der Instanz (mit Offset):** 
![image](https://user-images.githubusercontent.com/59330827/98403192-e3795780-2068-11eb-9424-9e81fac39b0c.png)

**Daraus resultiert diese Anzeige:**
![image](https://user-images.githubusercontent.com/59330827/98403118-bfb61180-2068-11eb-95ce-3c50cfade296.png)

Da ich bei "Aktuellen Tag ab Stunde X überspringen" 12 angegeben habe, sollte die heutige Abholung der Biotonne eigentlich übersprungen werden. 
Des Weiteren stimmen die "Zahlen" (Rest-Tage) nicht. 
Für mein Verständnis, sollte doch im Beispiel der Restabfalltonne (Abholung Montag, 9.11.) die Zahl 3 angezeigt werden und nicht 4. Wenn man vom heutigen Datum (Freitag, 6.11.) ausgeht.

Habe ich etwas falsch konfiguriert oder gibt es ein Problem mit der V1.0.0?

**Comment by norbgi** [comment]
bei mir erscheint gar kein Datum seit V1.0.0

![image](https://user-images.githubusercontent.com/58113317/98403110-bd53b780-2068-11eb-9b47-a479925cadf1.png)

**Comment by ThePoshExpert** [comment]
> bei mir erscheint gar kein Datum seit V1.0.0 bei Verwendung des Widgets
> 
> ![image](https://user-images.githubusercontent.com/58113317/98403110-bd53b780-2068-11eb-9b47-a479925cadf1.png)

dito

**Comment by klein0r** [comment]
@norbgi @ThePoshExpert Das ist i.d.R. durch ein Upload von Trashschedule und danach von VIS gelöst. Die Scripts haben sich geändert. Außerdem ist das hier OffTopic in diesem Issue

**Comment by ThePoshExpert** [comment]
Super, das war es. Sorry für den Offtopic Post, ich hatte nicht drauf geachtet. 

 

Von: Matthias Kleine <notifications@github.com> 
Gesendet: Samstag, 7. November 2020 09:37
An: klein0r/ioBroker.trashschedule <ioBroker.trashschedule@noreply.github.com>
Cc: ThePoshExpert <martin@baudermann.eu>; Mention <mention@noreply.github.com>
Betreff: Re: [klein0r/ioBroker.trashschedule] bei Verwendung von Offset keine korrekte Berechnung/Anzeige der Rest-Tage (#42)

 

@norbgi <https://github.com/norbgi>  @ThePoshExpert <https://github.com/ThePoshExpert>  Das ist i.d.R. durch ein Upload von Trashschedule und danach von VIS gelöst. Die Scripts haben sich geändert. Außerdem ist das hier OffTopic in diesem Issue

**Comment by klein0r** [comment]
@sly-1 Danke für den Report, kann ich bestätigen. Das Problem dabei ist, dass iCal mir scheinbar gar nicht mehr den Termin von gestern mitliefert. Somit wird der Termin auch nicht berücksichtigt. Das hatte ich nicht bedacht. Muss ich mir mal überlegen, wie ich das hinbekomme.

**Comment by klein0r** [comment]
> Abholung der **Biotonne** war heute (**6**.11.2020.)
> Ich benötige aber einen Offset von +1.

Wenn Du einen Offset von 1 konfigurierst, wäre aber die Biotonne auf den 7.11. verschoben worden. (6.11. + 1)

Ich habe noch einen Fehler in der Berechnung der Rest-Tage gefunden. Gibt gleich eine neue Verison.
Für mich klingt es aber so, als ob Du keinen Offset brauchst.

**Comment by sly-1** [comment]
Danke das du dich so schnell dem Thema angenommen hast. 
Im Google Kalender steht der Abholtermin richtig drin. 
Für z.B. Restabfalltonne Montag, 9.11., wenn ich den Offset auf 0 belasse, dann zeigt mir das Widget als Abholtermin Sonntag, 8.11. an. 
Hier stimmt was nicht. 
Kannst du das bitte prüfen?

**Comment by klein0r** [comment]
Auch mit Version 1.0.1?

**Comment by sly-1** [comment]
Sorry, konnte jetzt erst die 1.0.1 testen. 
Damit funktioniert es so wie es soll. 
Vielen Dank für deine schnelle Reaktion und die zur Verfügung gestellte v1.0.1.
