### ISSUE TITLE
Invalid Date im Widget mit 1.0.0

### ISSUE THREAD

**Issue by Negalein** [klein0r/ioBroker.trashschedule#44]
mit 1.0.0 steht im Widget "Invalid Date"

![Screenshot 2020-11-07 140727](https://user-images.githubusercontent.com/45309436/98442125-1ec86480-2103-11eb-8b39-7ffb2e619244.png)

mit 1.0.2 bleibt der Fehler

**Comment by klein0r** [comment]
Duplicate #41
