### ISSUE TITLE
Feature request: Provide ical-description as data point

### ISSUE THREAD

**Issue by NochnTim** [klein0r/ioBroker.trashschedule#47]
For certain waste types my waste management provides information like time window and pick-up location per ical description field. 
Would be great if this description could be provided simply as data point similar to "typestext" so it can be forwarded to a vis or telegram instance. 

BEGIN:VEVENT
DTSTART:20201116T050000Z
DTEND:20201116T160000Z
LOCATION;LANGUAGE=de:Somewhere nice
TRANSP:TRANSPARENT
SEQUENCE:0
UID:4f5b0609eb4beb0b2f74640541e18e0a
DTSTAMP:20201114T153800Z
CATEGORIES;LANGUAGE=de:Abfuhrtermine,
**DESCRIPTION**;LANGUAGE=de:Abfuhrtermin Problemmüll / Standort: Drei Ecken weiter um 11:15 - 12:00 Uhr am 16.11.2020
SUMMARY;LANGUAGE=de:Abfuhrtermin Problemmüll am 16.11.2020
PRIORITY:5
CLASS:PUBLIC
STATUS:CONFIRMED
BEGIN:VALARM
ACTION:DISPLAY
TRIGGER:-PT1440M
DESCRIPTION:ABFALLFRAKTION
SUMMARY:ABFUHRTERMIN!
DURATION:5
REPEAT:5
END:VALARM
END:VEVENT

**Comment by klein0r** [comment]
fixed in 1.0.4 (nextDescription)
