### ISSUE TITLE
Error spamming Sentry!

### ISSUE THREAD

**Issue by Apollon77** [klein0r/ioBroker.trashschedule#48]
https://sentry.iobroker.net/share/issue/ca9cde4109d94db4b245e82020c1c56f/

Please check and Fix!

**Comment by klein0r** [comment]
This is already fixed in 1.0.3 - how can I prevent reports for older versions?

**Comment by Apollon77** [comment]
First of all you should also mark the issues in sentry as fixed together with the relevant version. With this sentry makes sure to reopen the issue if also happening with a higher version. Also when I check it and see that errors come in in mass on a solved issue I can blacklist the solved version

**Comment by Apollon77** [comment]
I blacklisted theversion and solved the issue
