### ISSUE TITLE
[Widget] Name der Tonne ausblenden

### ISSUE THREAD

**Issue by marcus0815** [klein0r/ioBroker.trashschedule#49]
Es wäre toll, wenn auch der Name der Tonnen ausgeblendet werden kann.
Anhand der Farbe ist es ja schon eindeutig, um welche Tonne es sich handelt 👍 

Danke vorab!

**Comment by hyperbit00** [comment]
Ich klinke mich hier mal mit ein =)

* Name der Tonne raus (option)
* Tonnenbild ändern (option)
* nur einzelne Tonnen darstellen (momentan stellt er alle dar)
* alle Schriftgrößen einzeln änderbar machen

Danke für Deine ansonsten saustarke Arbeit!!!

**Comment by derweidner0815** [comment]
1.) Es ist ein cooler Adapter , Danke für die Arbeit.

- Ich schließe mich meinen Vorredner an, es wäre aber schöner wenn man Schriftgröße, Tonnengröße und etc. noch ändern könnte. 

Danke und Grüße

**Comment by klein0r** [comment]
Ich möchte möglichst vermeiden, dass die Konfiguration zu mächtig wird. Ansonsten wird man wieder erschlagen. Und umso mehr man konfigurieren kann, desto mehr kann man auch falsch machen und umso mehr gibt es für mich bei der Pflege vom Widget zu beachten.

Für andere Bilder bei den Tonnen bin ich grundsätzlich offen. Allerdings brauche ich dann ein SVG in Graustufen als Vorlage. Weil aktuell wird das SVG mit JavaScript auseinandergenommen und dann entsprechend der Helligkeitswerte relativ zur ausgewählten Farbe eingefärbt. "Mal eben" andere Bilder bereitstellen ist daher nicht möglich.

**Comment by klein0r** [comment]
In 1.4.0 geht das jetzt
