### ISSUE TITLE
Tonne fehlt plötzlich in der Visualisierung

### ISSUE THREAD

**Issue by MCepheus** [klein0r/ioBroker.trashschedule#50]
Hi, ich habe gerade ein merkwürdiges Problem. Seit heute ist plötzlich eine der Tonnen in meiner Visualisieung verschwunden.
Kann es evtl. damit zusammenhängen, dass heute bei mir Abholtermin und die Tonne damit als 0-Tage gelistet ist? Verwunderlich ist hierbei auch, das in den Objekten zur Tonne keine Zahl "0" sondern der Wert "null" eingetragen ist. Das bringt meine Abhängigkeiten in der VIS auch ganz schön durcheinander. Bisher war mir das Verhalten noch nie aufgefallen. Wurde in der 1.0.3 irgendwas in der Hinsicht verändert?
![Trash](https://user-images.githubusercontent.com/72047389/101381694-591a5280-38b7-11eb-8853-c0fae79dc63b.PNG)

Gruß

**Comment by klein0r** [comment]
Null ist nicht 0, richtig. Also konnte KEIN Termin in Zukunft gefunden werden. Das liegt wahrscheinlich an einer falschen Konfiguration von iCal oder dem Kalender. Es geht ja dem Jahresende entgegen - eventuell war das die letzte Abholung im Kalender dieses Jahr und es wurde einfach noch kein Termin für 2021 hinzugefügt?

**Comment by MCepheus** [comment]
Hi Matthias,
das war auch der Fehler. Ich habe heute manuell die neuen Daten für 2021 eingegeben, da mein Dienstleister die Abholungstermiene der einen Tonne (noch) nicht in den Kalender eingepflegt hat.
Jetzt klappt alles wieder wie es soll. Dann weiß ich ja fürs nächte Mal Bescheid.
Könnte man das nich in der Json abfangen und darauf hinweiesen?
---
offtopic
Danke übrigens für deinen Iobroker-Kurs. Hab die für mich bisher wichtigsten Dinge durch. Kommt da irgendwann auch mal ein Update? An Blocklytipps oder Vis bin ich immer interessiert. ;) Bindings sind für mich noch ein Buch mit sieben Siegeln...

Viele Grüße

**Comment by klein0r** [comment]
> Kommt da irgendwann auch mal ein Update? An Blocklytipps oder Vis bin ich immer interessiert.

Ja, ist natürlich geplant da weiter zu machen. Momentan habe ich nur sehr viele Themen auf einmal, wo es weiter gehen muss. YouTube hat ja z.B. fast den kompletten Stillstand erreicht, die Adapter-Entwicklung hat mich jetzt auch immer wieder viel Zeit gekostet und ansonsten kommen so 100 Mails am Tag rein. Alles etwas viel auf einmal.
