### ISSUE TITLE
"0 Tage" am Abholtag anzeigen?

### ISSUE THREAD

**Issue by tijo82** [klein0r/ioBroker.trashschedule#51]
Gibt es eine Möglichkeit am Abholtag für DaysLeft noch "0" anzuzeigen und nicht schon den nächsten Termin?

Besten Dank für den Adapter :)
Tim

**Comment by klein0r** [comment]
Ja, das passiert ja sogar. Erst ab der konfigurierten Uhrzeit / Stunde wird die heutige Abholung ignoriert und der nächste Termin angezeigt.

**Comment by tijo82** [comment]
ich habe bei mir "Aktuellen Tag ab Stunde X überspringen" auf 18 stehen ... allerdings wird für eine heute abgeholte Tonne nicht mehr 0 angezeigt. Kann das damit zusammenhängen, wann ich bei mir deinen Adapter neu starte? (bei mir im Moment so: Um 02:01 und 20:01 jeden Tag)

**Comment by klein0r** [comment]
Ne, eigentlich kann das damit nix zu tun haben. Wird immer neu berechnet und kommt zu dem gleichen Ergebnis.
Warum startest Du den überhaupt neu?

**Comment by tijo82** [comment]
Sorry, wer lesen kann, ist im Vorteil.... Ich hatte "Hide Start-End of events" in der iCal Instanz falsch gesetzt...

Danke Dir!
