### ISSUE TITLE
Nichts zu sehen in APP Iobroker.vis

### ISSUE THREAD

**Issue by DeUser** [klein0r/ioBroker.trashschedule#53]
Hallo,
ich habe gestern erfolgreich das trashscheudule in meine Visualisierung eingebaut. 
Ich habe das Problem das ich das Widget auf meinem Tablet (läuft die App Iobroker.vis) nicht sehe. Wenn ich aber über einen Browser den Link zu meiner Visualisierung öffne ist alles gut.
Mache ich da was falsch?

**Comment by klein0r** [comment]
Für die App müssen die Widgets scheinbar separat vom Entwickler der App eingepflegt werden. Dazu gab es hier schon diverse Issues. Also bitte dort einen Issue öffnen oder den Fully Kiosk Browser nutzen

Siehe auch FAQ

https://github.com/klein0r/ioBroker.trashschedule/blob/master/faq_de.md
