### ISSUE TITLE
Datenpunkte werden mit Leerzeichen angelegt

### ISSUE THREAD

**Issue by testit2020** [klein0r/ioBroker.trashschedule#55]
Datenpunkte werden in ioBroker eigentlich nicht mit Leerzeichen angelegt.
![image](https://user-images.githubusercontent.com/68483974/104824400-9e845500-5851-11eb-943e-66a36ba09e07.png)

Da es z.B. in jarvis nicht mehr möglich ist solche DP auszuwählen und zu integrieren, bitte ich dies entsprechend anzupassen.
Vielen Dank.

**Comment by klein0r** [comment]
Gibt es eine Funktion, welche mir aus einem String alle nicht erlaubten Zeichen für einen Datenpunkt entfernt?

Ich dachte mir: Alles wird im ioBroker validiert. Wenn Leerzeichen nicht abgelehnt werden, sind sie wohl erlaubt.
Gibt es Guidelines, wo man das nachlesen kann?

**Comment by testit2020** [comment]
Replace Funktion?

**Comment by klein0r** [comment]
Okay, dann erlaube ich halt nur noch kleine Buchstaben und schmeiße den Rest raus ....
Ich denke Du weißt genau was ich meinte 😄

**Comment by testit2020** [comment]
Ersetze doch einfach Leerzeichen mit "_".

**Comment by klein0r** [comment]
Daher ja die Frage, was eigentlich erlaubt ist.
Was ist denn mit Umlauten oder Sonderzeichen? Punkte sind ja auch immer ein Thema. Also wenn ich das schonmal anfasse und damit allen Ihre Datenpunkte aktuelle zerschieße / ungültig mache, dann möchte ich es halt einmal ordentlich machen.

**Comment by testit2020** [comment]
https://forum.iobroker.net/topic/30668/jarvis-v2-1-0-just-another-remarkable-vis/3117

**Comment by klein0r** [comment]
Das Problem ist, dass es halt wieder ein Breaking Change ist für viele. 😢 
Damit generiere ich mir hunderte Support-Mails und Issues.

Am besten zwischenzeitlich einfach den Typ so benennen, dass kein Leerzeichen enthalten ist. Dann kannst Du diesen ja auch in Jarvis auswählen.

**Comment by testit2020** [comment]
Ok. Danke.

**Comment by klein0r** [comment]
Aber Version 1.1.0 wird alles aufgeräumt. Die ersten Beschwerden kommen schon rein ... siehe #58

**Comment by testit2020** [comment]
Langfristig auf jeden Fall die richtige Entscheidung.  Vielen Dank. Hab es bei mir schon geändert.

**Comment by klein0r** [comment]
Ja, lieber jetzt, als mit einer noch größeren Nutzerbasis... Nur ärgerlich, dass es jetzt schon die zweite größere Änderung in kurzer Zeit ist. Hoffentlich die letzte.

**Comment by klein0r** [comment]
> Langfristig auf jeden Fall die richtige Entscheidung.

Ja schon richtig - nur leidet das Vertrauen in den Adapter wenn ich ständig etwas ändere. Dann muss man sich wieder erklären usw. Wer kein Stress haben möchte, lässt also am besten die Fehler in seinen Adaptern drin 😄  Habe ich jetzt auch gelernt.

**Comment by testit2020** [comment]
Du musst es vielleicht in einem Post in iobroker erklären, warum du das gemacht hast. Und direkt oben in GITHUB zu deinem Adapter ganz in GROSS am Anfang.
