### ISSUE TITLE
js-controller 3.2.2

### ISSUE THREAD

**Issue by Brainbug01** [klein0r/ioBroker.trashschedule#56]
```
trashschedule.0 | 2021-01-22 19:40:07.810 | warn | (17299) State "trashschedule.0.type.Graue Tonne.nextDescription" has no existing object, this might lead to an error in future versions
-- | -- | -- | --
trashschedule.0 | 2021-01-22 19:40:07.809 | warn | (17299) State "trashschedule.0.type.Gelber Sack.nextDescription" has no existing object, this might lead to an error in future versions
```

**Comment by Feuer-sturm** [comment]
Warnung "nextDescription" has no existing object" ist bei mir erstmals mit Adapter 1.0.4 unter js-controller 3.2.8 aufgetreten:

Für Papiermüll und Restmüll kommt die Meldung komischerweise bei mir nicht.


trashschedule.0 | 2021-01-23 20:57:09.063 | warn | (30413) State "trashschedule.0.type.Plastikmüll.nextDescription" has no existing object, this might lead to an error in future versions
-- | -- | -- | --
trashschedule.0 | 2021-01-23 20:57:09.061 | warn | (30413) State "trashschedule.0.type.Biomüll.nextDescription" has no existing object, this might lead to an error in future versions
trashschedule.0 | 2021-01-23 20:57:08.732 | info | (30413) starting. Version 1.0.4 in /opt/iobroker/node_modules/iobroker.trashschedule, node: v12.18.3, js-controller: 3.2.8

**Comment by klein0r** [comment]
Gucke ich mir gleich an!

**Comment by Gosuwaldbear** [comment]
Der Adapter findet bei mir auch nur Items in dem ical Kalender, wenn ich den Hauptkalender einbinde. Sobald ich einen separat erstellten Kalender, in dem die Abfalltermine sind im ical hinterlege, findet der Adapter keine Einträge mehr. Der ical listet die Items korrekt auf.

Kalender liegen bei mir, wie in deinem Video bei Google und nutze dem Link für die "Privatadresse im ical Format".
