### ISSUE TITLE
Objekt "null days" statt "0 days"

### ISSUE THREAD

**Issue by capitaenz** [klein0r/ioBroker.trashschedule#57]
Hallo zusammen,

finde keine Antwort auf mein Problem und vermutlich ist es nur eine Kleinigkeit die ich übersehe.
Ich habe die Version 1.1.0 installiert und es werden in den Objekten die Tage heruntergezählt: 4,3,2,1, null.
Null dann als Wort. Wie kann ich das ändern, oder ist es ein Fehler?
![null](https://user-images.githubusercontent.com/1240236/105750276-d7ed4c80-5f44-11eb-8a6d-98c8e2efd9cf.JPG)

VG
Leif

**Comment by klein0r** [comment]
Hallo Leif,

null heißt eigentlich, dass kein Termin gefunden wurde (siehe auch `nextDateFound` = `false`.
Numerisch 0 wäre heute. Wird schwer zu helfen ohne die genaue Konfiguration zu kennen.

Eventuell hilft Dir das FAQ bei der Fehlersuche?
https://github.com/klein0r/ioBroker.trashschedule/blob/master/faq_de.md

**Comment by capitaenz** [comment]
Moin Matthias,

danke für die Rückmeldung.
Die Datei kommt direkt von der Hamburger Stadtreinigung: [Stadtreinigung Hamburg](https://www.stadtreinigung.hamburg/privatkunden/abfuhrkalender/index.html)
Könntest du es nicht vielleicht ermöglichen, wenn kein Termin gefunden wird (auf Wunsch) eine "0" geliefert wird?
Das wäre eine Tolle Sache!

VG
Leif

**Comment by klein0r** [comment]
Das wäre doch aber eine falsche Information?

**Comment by capitaenz** [comment]
Der Kalender verhält sich so, dass am Abholtag immer "null" angezeigt wird... Wenn statt "null" eine "0" übergeben würde, dann wäre mir mit dem Kalender der Hamburger Stadtreinigung geholfen.
Ja, die Information wäre falsch, deswegen die Idee mit "auf Wunsch".

**Comment by klein0r** [comment]
Die Hamburger scheinen speziell zu sein - dafür ist ja auch schon das Feature reingekommen, dass man die Termine generell verschieben kann 😄

**Comment by capitaenz** [comment]
Ich hoffe ich mache keinen Konfigurationsfehler, aber ich habe mir den ical und deinen Adapter angesehen und diverse Sachen probiert, immer mit dem Ergebnis, das ich "null" angezeigt bekomme.
Um den Faktor Mensch, also mich, auszuschließen, kann ich vielleicht noch etwas Testen oder Daten vom Kalender hier hochladen?

VG
Leif

**Comment by klein0r** [comment]
Am Abholtag wird "null" angezeigt:

- Wenn die aktuelle Stunde später ist als "Aktuellen Tag ab Stunde X überspringen", wird der heutige Abholtag ignoriert und weiter in der Zukunft im Kalender gesucht
- Wenn dann aber iCal nicht so konfiguriert ist, um den nächsten Termin "sehen zu können" (Tagesvorschau), kommt "null" raus und es wird kein Abholtermin für den Typen gefunden

Also an diesen beiden Stellschrauben würde ich mal drehen.

**Comment by capitaenz** [comment]
OK, verstanden.
Jedoch wenn ich in deinem Adapter im offset auf minus gehe, um eine Abholung zu "provozieren", dann steht dort auch "null days". Ical dürfte somit doch dann kein Problem mit der Tagesvorschau haben, oder? Steht sowieso auf 15 Tage.

**Comment by klein0r** [comment]
Wenn heute der 27.1. ist und an dem 27.1. eine Abholung im Kalender steht, wird diese Abholung mit offset -1 in die Vergangenheit geschoben (26.1.) und somit ignoriert (weil wäre ja dann gestern dran gewesen).

**Comment by ChrisWoehrle** [comment]
> OK, verstanden.
> Jedoch wenn ich in deinem Adapter im offset auf minus gehe, um eine Abholung zu "provozieren", dann steht dort auch "null days". Ical dürfte somit doch dann kein Problem mit der Tagesvorschau haben, oder? Steht sowieso auf 15 Tage.

Du musst im iCal Adapter ebenfalls in die Vergangenheit reisen, sonst wird das nichts.

**Comment by Sasch72** [comment]
Hallo in die Runde!
Ich bin entweder blind oder blöd oder beides.
Mein Problem ist folgendes:
Ich haben den Adapter erfolgreich eingerichtet und auch schon ins VIS eingebunden gehabt. 
Dann habe ich mir die Woch egedacht, es wäre doch auch schön wenn du benachrichtigst wiest wenn ein Termin ansteht. Also habe ich das Script aus dem Masterkurs eingebunden. (Das "neue" Script von Matthias habe ich heut erst gesehen.)
Heute habe ich dann festgestellt das die Ansicht nicht mehr aktualisiert wird.
Also habe ich das Script wieder gelöscht. 
Die Aktualisierung funktionierte trotzdem nicht . In den Adaptern steht "null days". Dann habe ich den Ical Adapter und den Müll Adapter gelöscht und noch einmal neu konfiguriert. Ical so wie im Masterkurs , zusätzlich habe ich noch Anzeigen ausgewählt.
Immer noch der gleich Fehler.
Im Log steht:
"nextAfter has no entries. Check configuration of iCal and trashschedule!"
"no events matches type "Restmüll" with match "Restmüll-Tonne". Check configuration of iCal (increase preview) and trashschedule!"
Das sind zwei Beispiele. Die Vorschau steht auf 90 Tage.
Habt ihr noch eine Idee was das sein kann?
Danke!

**Comment by klein0r** [comment]
@Sasch72 Ich nehme an, die FAQ zum Adapter hast Du komplett gelesen? :)
https://github.com/klein0r/ioBroker.trashschedule/blob/master/faq_de.md

Falls Du also die "Ereignisse" aus dem iCal Adapter verwendest, musst Du einen Haken bei "Anzeigen" setzen. Sonst werden die Termine von iCal gefiltert und sind für Trashschedule nicht mehr auffindbar.

**Comment by Sasch72** [comment]
@klein0r Ja habe ich und die Videos habe ich im Mastekurs auch noch einmal angesehen. Den Fehler habe ich mittlerweile gefunden. Ich hatte im Reiter Abfalltypen "Genauer Treffer" ausgewählt. Habe eigentlich alles so benannt wie es im Abfallkalender steht.  Den habe ich mal deaktiviert und schon hat es wieder funktioniert. Frag mich nicht warum. Am dem Adapter habe ich ja nichts geändert gehabt. Danke für deine Antwort.
