### ISSUE TITLE
1.1.0 - Object ID wird plötzlich klein geschrieben

### ISSUE THREAD

**Issue by tobasium** [klein0r/ioBroker.trashschedule#58]
Hallo, mit dem letzten Update wurden Plötzlich die Datenpunkte umbenannt was sich natürlich komplett auf die VIS und scripte auswirkt.

Version 1.0.6 --> trashschedule.0.type.Altpapier
Version 1.1.0 --> trashschedule.0.type.altpapier

Muss ich das jetzt anpassen oder ist das nur ein Fehler?

**Comment by klein0r** [comment]
Das ist korrekt und bleibt so (daher auch der Sprung auf 1.1.x von 1.0.x).

Ich hatte vermehrt Anfragen mit Problemen, dass die Datenpunkte keine Sonderzeichen enthalten dürfen.
Diese werden nun aufgeräumt und auf CamelCase umgestellt.

"Gelber Sack" wird zum Beispiel zu "gelberSack"

Leerzeichen und andere Sonderzeichen werden also jetzt entfernt.
Ich hatte gehofft, dass die wenigsten die Datenpunkten der Typen direkt verwenden, sondern eher auf next / nextAfter gehen bzw. das offizielle Widget nutzen - denn da gibt es dann keinen Breaking Change
