### ISSUE TITLE
Abfalltypen werden nicht erkannt

### ISSUE THREAD

**Issue by chipDE** [klein0r/ioBroker.trashschedule#59]
Hallo,

ich habe das Problem, dass obwohl die von ical kommenden Termine korrekt in trashschedule hineinlaufen, dieser nicht die Abfalltypen erkennt und dann mit einem "no events matches" endet.

Wie auf youtube gewünscht die Screen

ical-Adapter:
![ical_haupt](https://user-images.githubusercontent.com/16877169/106893559-04942780-66ee-11eb-8c55-5a13efc6195b.jpg)
![ical_kalender](https://user-images.githubusercontent.com/16877169/106893570-078f1800-66ee-11eb-8465-f935705a9c28.jpg)
![ical_ereignisse](https://user-images.githubusercontent.com/16877169/106893574-08c04500-66ee-11eb-8a37-c79e18cf9c48.jpg)

trashschedule:
![trash_haupt](https://user-images.githubusercontent.com/16877169/106893758-4a50f000-66ee-11eb-8081-56d5cebf04a4.jpg)
![trash_typen](https://user-images.githubusercontent.com/16877169/106893760-4b821d00-66ee-11eb-97f2-59e837004c95.jpg)

und das Debug-Logfile.

[trash_debug.log](https://github.com/klein0r/ioBroker.trashschedule/files/5925688/trash_debug.log)

verwendeter ical:

[Leerungstermine141676.zip](https://github.com/klein0r/ioBroker.trashschedule/files/5925826/Leerungstermine141676.zip)

mfg

**Comment by chipDE** [comment]
Hier noch einmal damit das Log etwas Übersichtlicher ist mit den ical Einstellungen auf 30 Tage:

![ical_30](https://user-images.githubusercontent.com/16877169/106895158-2bebf400-66f0-11eb-98bd-70fe77255e8a.jpg)

[trash_debug_30.log](https://github.com/klein0r/ioBroker.trashschedule/files/5925773/trash_debug_30.log)

**Comment by klein0r** [comment]
Kann es sein, dass Du bei "gilt für Termine" ein Leerzeichen vor "Restabfall" hast?

**Comment by chipDE** [comment]
OMG *Kopf Tisch*, genau das war es. Klassischer Fall von DAU.

**Comment by klein0r** [comment]
Ich habe mal einen Hinweis eingefügt, falls der zu suchende Treffer mit Leerzeichen beginnt oder endet.
