### ISSUE TITLE
Datenpunkte werden nicht aktualisiert, wenn kein entsprechender Kalendereintrag vorhanden ist

### ISSUE THREAD

**Issue by ivosch68** [klein0r/ioBroker.trashschedule#6]
**Fehlerbeschreibung**  
Datenpunkte werden nicht aktualisiert, wenn kein entsprechender Kalendereintrag zu dem Abfall-Typ  vorhanden ist.

**Schritte zum Reproduzieren**  
Annahme: Es ist in der Instanz ein Abfall-Typ *Weihnachtsbaum* definiert.
1. Lege einen Kalendereintrag mit Betreff *Weihnachtsbaum*, z.B. heute in zwei Tagen an. Bemerkung: Es muss der einzige zukünftige Eintrag dieses Typs sein.
2. Warte bis die entsprechenden Datenpunkte unter ``trashschedule.0.type`` gefüllt sind.
3. Lösche den in 1. angelegten Kalendereintrag.

Fehler: Auch nachdem der Eintrag vom ical Adapter wieder gelöscht (weg-synchronisiert) wurde, werden die Datenpunkte unter ``trashschedule.0.type`` nicht aktualisiert.

**Erwartetes Verhalten**
1. Wenn kein entsprechender Kalendereintrag vorhanden ist, sollten die Datenpunkte unter ``trashschedule.0.type`` auf Defaultwerte gesetzt werden.
2. Diese Defaultwerte sollten auch initial gesetzt werden, da es sonst bei der Abfrage der Datenpunkte zu einer Warnung im javascript Adapter kommt.

**Versionen:**  
 - Adapter version: 0.0.4
 - JS-Controller version: 2.2.9
 - Node version: v10.19.0
 - Operating system: linux

**Comment by klein0r** [comment]
Verstehe, meine Frage wäre nun, was denn der Default für die einzelnen Werte sein soll?

**Comment by ivosch68** [comment]
> Verstehe, meine Frage wäre nun, was denn der Default für die einzelnen Werte sein soll?

Meine spontane Idee wäre einen leeren String für die Datumsattribute (nextdate, nextdateformat) und -1 für die numerischen Attribute (nextweekday, daysleft) zu benutzen. Das sollte inhaltlich nicht zu Verwirrungen führen und ich habe die Hoffnung, dass dann keine Warnungen mehr beim Lesen geworfen werden.

**Comment by ivosch68** [comment]
Ich habe nochmal darüber nachgedacht. Defaultwerte bei Daten machen nicht wirklich Sinn. 

Daher würde ich wohl die Datenfelder unberührt lassen und entweder die numerischen Attribute auf -1 setzen oder einen neuen booleschen Datenpunkt, z.B. ``eventFound``, einführen, der, je nachdem ob ein Datum gefunden wurde oder nicht, auf true oder false gesetzt wird.

Um alles andere muss sich dann halt der Consumer kümmern, was aber meiner Meinung nach in Ordnung ist.

**Comment by none007** [comment]
Ich bin gerade auch über die Weihnachtsbäume gestolpert.  Die numerischen Atrribute auf -1 setzten würde aber bei Abfragen bzgl. <= Tage zu Problemen führen oder?

Da wäre evtl. ein unwahrscheinlicher Wert wie z.B. 400 doch sinnvoller. Sobald dann ein Kalendereintrag im Suchfenster auftaucht wird der richtige Wert gesetzt. Nach dem entsprechenden Termin wird im Fall, es taucht im Suchfenster wieder kein neuer Termin auf, der Wert wieder 400 gesetzt. Etwaige Abfragen für z.B. json müssten halt dann die 400 berücksichtigen als nicht vorhanden. 

Könnte das klappen oder sehe ich da was völlig falsch....

**Comment by ivosch68** [comment]
Ich würde 999 nehmen, weil du eh prüfst, ob minDays < 999 ist.
Damit sollte es aber klappen.

**Comment by klein0r** [comment]
@none007 Naja, rein logisch sind eben alle möglichen Werte in der Zukunft gültig. Auch 999. Wobei wohl kaum jemand seinen Kalender so weit in die Zukunft stellen wird 😄 Genau diese Randbedingungen sind immer schwer zu handhaben.

-1 wäre daher eventuell sinnvoller, da Termine aus der Vergangenheit ja nie berücksichtigt werden. Nur was mache ich dann mit den anderen Feldern, damit das konsistent ist. Ich kann als Datum ja schlecht den Wert von gestern eintragen zum Beispiel.

**Comment by ivosch68** [comment]
Schwierig ... Konsistenz wird man da nicht hinbekommen.
Damit spricht vieles für einen zusätzlichen Datenpunkt, der anzeigt, ob ein Eintrag gefunden wurde oder nicht.

> ... oder einen neuen booleschen Datenpunkt, z.B. `eventFound`, einführen, der, je nachdem ob ein Datum gefunden wurde oder nicht, auf true oder false gesetzt wird.
