### ISSUE TITLE
Änderung bei trashschedule.0.next.typesText 

### ISSUE THREAD

**Issue by jlegen** [klein0r/ioBroker.trashschedule#60]
Hallo,
bislang konnte ich bequem "trashschedule.0.next.typesText" benutzen, dank des " " nach den Kommata. Nun - nach 1-2 Updates oder so ;) - ist nun bei V1.1.1 offenbar trashschedule.0.next.typesText identisch zu trashschedule.0.next.types, d.h. die Aufzählung enthält keine Blanks mehr. Das führt dazu, dass z.B. die Iqontrol-Kacheln den Text nicht mehr vollständig anzeigen können, mangels Möglichkeit zum Umbruch nach einem Komma.
Also statt 
"Papiertonne,
Biotonne"
steht da nun "Papiertonne,Bioto".
Lässt sich das evtl. wieder ändern? Falls nicht, stellte sich mir dann die Frage, was wohl der Unterschied zwischen trashschedule.0.next.typesText und trashschedule.0.next.types sein könnte... :)

**Comment by klein0r** [comment]
Das Trennzeichen kannst Du doch selbst in den Einstellungen konfigurieren? Mach halt ein Leerzeichen dazu 😄

**Comment by jlegen** [comment]
och komm, die Option hast du da doch gerade schnell reingebastelt, so blind konnte ich nicht sein ;-) 
Vielen Dank!

**Comment by klein0r** [comment]
Stimmt die gibt es erst seit 0.0.1 oder so 😄
