### ISSUE TITLE
Warnings mit 1.1.1

### ISSUE THREAD

**Issue by hytrek** [klein0r/ioBroker.trashschedule#61]
Hi Mathias, 
das steht seit heute im LOG
Zumindest fällt es mir heut erst auf... Wegduck

Oder habe ich was falsch gemacht? Wenn ja... HÜLFE... was?

`

javascript.0 | 2021-02-08 19:00:00.018 | warn | (1729) at processTimers (internal/timers.js:497:7)
-- | -- | -- | --
javascript.0 | 2021-02-08 19:00:00.018 | warn | (1729) at listOnTimeout (internal/timers.js:554:17)
javascript.0 | 2021-02-08 19:00:00.018 | warn | (1729) at Timeout._onTimeout (/opt/iobroker/node_modules/node-schedule/lib/schedule.js:510:7)
javascript.0 | 2021-02-08 19:00:00.018 | warn | (1729) at /opt/iobroker/node_modules/node-schedule/lib/schedule.js:552:11
javascript.0 | 2021-02-08 19:00:00.018 | warn | (1729) at Job.invoke (/opt/iobroker/node_modules/node-schedule/lib/schedule.js:173:10)
javascript.0 | 2021-02-08 19:00:00.018 | warn | (1729) at Job.job (/opt/iobroker/node_modules/iobroker.javascript/lib/sandbox.js:1297:34)
javascript.0 | 2021-02-08 19:00:00.017 | warn | (1729) at Object.<anonymous> (script.js.Telegram.Müllabholung.Müllabholung_Morgen_Kopieren:22:9)
javascript.0 | 2021-02-08 19:00:00.007 | warn | (1729) getState "ical.0.events.1.Sperrmuell" not found (3)

`

**Comment by klein0r** [comment]
Mit den iCal Events habe ich nichts zu tun 😄 
"ical.0.events.1.Sperrmuell" kommt ja vom iCal Adapter unter "Ereignisse"
