### ISSUE TITLE
Keine reaktion bei "ical Instanz"

### ISSUE THREAD

**Issue by marsmaennchen** [klein0r/ioBroker.trashschedule#63]
Wenn ich bei Haupteinstellungen die Ical Instanz eingeben will (Privatadresse im iCal Format?) dann gibt es keine Reaktion.
Kein Pop-Up, kein Pulldown menü, keine Möglichkeit etwas  auf der Linie einzugeben einzugeben.

**Comment by klein0r** [comment]
Klingt nach einem Problem mit iCal und nicht mit diesem Adapter?

**Comment by marsmaennchen** [comment]
Nun ja, wenn ich bei der besagten Linie im Hauptmenü der Instanz etwas eingeben will, egal was, kann ich nichts eingeben weil die Instanz dort auf nichts reagiert. Bei den anderen Eingabemöglichkeiten würde es gehen. Sollte man dort bei Ical Instanz die privatadresse im ical Format angeben?

**Comment by marsmaennchen** [comment]
![trash1](https://user-images.githubusercontent.com/33393715/111074338-cbb45300-84e2-11eb-9469-36a4ae34b82a.JPG)
![trash2](https://user-images.githubusercontent.com/33393715/111074346-d2db6100-84e2-11eb-8908-fb7a338dd902.JPG)
Bei der gelben Linie gehört meines Verständnisses nach die ICal Privatadresse (Google Kalender) rein. Der Mauszeiger ändert sich zwar zu einer Hand wenn ich dort bin, aber er lässt mich nichts eingeben, reagiert nicht.

**Comment by klein0r** [comment]
Nein, das ist ein Dropdown und dort wählt man die iCal Instanz aus, welche die Termine holt.
Siehe: https://www.youtube.com/watch?v=v9-6LJph_8Q

Ich mache hier zu
