### ISSUE TITLE
Auf Ipad 2 oder 3 keine Widgets

### ISSUE THREAD

**Issue by fighterzg6** [klein0r/ioBroker.trashschedule#64]
Hallo, 

es werden keine Tonnen auf iPad 2 oder 3 angezeigt ! iPad Air 2 oder pro funktioniert! warum das????

**Comment by klein0r** [comment]
Erstmal werden so alte Geräte generell von den aktuellen VIS Versionen (socket-io) nicht mehr unterstützt und die wurden daher auch nicht mit dem Adapter getestet. Die sind ja auch bei Apple schon aus dem Support gefallen.

**Comment by fighterzg6** [comment]
Alle anderen Widgets funktionieren tadellos. Und die ioBroker App für die vis sagt minimale iOS Version 9.3 , iPad 2 hat 9.5! Aber abgesehen davon finde ich diese Geräte eigentlich ideal für sowas! Denke es wäre kein Problem eine Version für ältere Geräte zu veröffentlichten! Würde dafür sogar bezahlen!

**Comment by klein0r** [comment]
Dann bräuchte ich nur erstmal so ein Gerät um den Fehler zu finden. Und das lohnt sich wohl aktuell nicht mehr :)

Bekommst Du irgend eine Fehlermeldung die mir helfen könnte?

**Comment by fighterzg6** [comment]
Leider nein! Auf Mac Book Air, iPad Pro, iPad Air 2 alles top top! Nur auf den alten iPads gehen die „ Mülheimer „ nicht! Weder über die App noch über den Safari Browser! Denke es hat was mit dem Widget zu tun!

**Comment by fighterzg6** [comment]
Könnte dir so ein Gerät zukommen lassen
