### ISSUE TITLE
State value has wrong type (js-controller 3.3.x)

### ISSUE THREAD

**Issue by Feuer-sturm** [klein0r/ioBroker.trashschedule#65]
js-controller: 3.3.1
Admin 5.0.11
Trash Schedule Adapter: 1.1.1

Using new js-controller 3.3.1 will throw the following warnings:

```
trashschedule.0 (969) State value to set for "trashschedule.0.next.weekday" has wrong type "number" but has to be "string"
trashschedule.0 (969) State value to set for "trashschedule.0.nextAfter.weekday" has wrong type "number" but has to be "string"
trashschedule.0 (969) State value to set for "trashschedule.0.type.biomüll.nextWeekday" has wrong type "number" but has to be "string"
trashschedule.0 (969) State value to set for "trashschedule.0.type.papiermüll.nextWeekday" has wrong type "number" but has to be "string"
trashschedule.0 (969) State value to set for "trashschedule.0.type.plastikmüll.nextWeekday" has wrong type "number" but has to be "string"
trashschedule.0 (969) State value to set for "trashschedule.0.type.restmüll.nextWeekday" has wrong type "number" but has to be "string"
```

**Comment by TheBrain26** [comment]
Same Issues

ioBroker/ioBroker.js-controller#1299 (comment)

**Comment by frankbullitt** [comment]
Yes! Same here!


trashschedule.0 | 2021-05-01 00:30:08.444 | warn | (2462) State value to set for "trashschedule.0.nextAfter.weekday" has wrong type "number" but has to be "string"
-- | -- | -- | --
trashschedule.0 | 2021-05-01 00:30:08.443 | warn | (2462) State value to set for "trashschedule.0.next.weekday" has wrong type "number" but has to be "string"
trashschedule.0 | 2021-05-01 00:30:08.433 | warn | (2462) State value to set for "trashschedule.0.type.papiertonne.nextWeekday" has wrong type "number" but has to be "string"
trashschedule.0 | 2021-05-01 00:30:08.431 | warn | (2462) State value to set for "trashschedule.0.type.restmüll.nextWeekday" has wrong type "number" but has to be "string"
trashschedule.0 | 2021-05-01 00:30:08.430 | warn | (2462) State value to set for "trashschedule.0.type.biotonne.nextWeekday" has wrong type "number" but has to be "string"
trashschedule.0 | 2021-05-01 00:30:08.428 | warn | (2462) State value to set for "trashschedule.0.type.gelbeTonne.nextWeekday" has wrong type "number" but has to be "string"

**Comment by WolfgangGr** [comment]
**Describe the bug**  
After updating of js-controller 3.2.16 to 3.3.2 it will be logged a warning
`2021-04-30 20:52:41.808 - warn: trashschedule.0 (6490) State value to set for "trashschedule.0.type.bioabfall.nextWeekday" has wrong type "number" but has to be "string"`

**To Reproduce**  
Steps to reproduce the behavior:
Update to js-controller 3.3.2

**Expected behavior**  
no warning

**Screenshots & Logfiles**  
`2021-04-30 20:52:41.808 - warn: trashschedule.0 (6490) State value to set for "trashschedule.0.type.bioabfall.nextWeekday" has wrong type "number" but has to be "string"
2021-04-30 20:52:41.831 - warn: trashschedule.0 (6490) State value to set for "trashschedule.0.next.weekday" has wrong type "number" but has to be "string"
2021-04-30 20:52:41.833 - warn: trashschedule.0 (6490) State value to set for "trashschedule.0.nextAfter.weekday" has wrong type "number" but has to be "string"`

**Versions:**  
 - Adapter version: <1.1.1>
 - JS-Controller version: <3.3.2>
 - Node version: <12.22.1>
 - Operating system: <Raspian buster 10>

**Comment by klein0r** [comment]
The state has already the type `string`

https://github.com/klein0r/ioBroker.trashschedule/blob/a9596f8d6561479ea9d7cb8070a36871786985d9/main.js#L106-L116

Please delete the entire channel and restart the trash schedule adapter.

**Comment by Feuer-sturm** [comment]
@klein0r I stopped trash schedule adapter and deleted the whole objects for "trash schedule" and the started the adapter once again.


```
01 May 2021 21:02:16.787 iobrokertestsystem trashschedule.0 (6892) State value to set for "trashschedule.0.nextAfter.weekday" has to be type "string" but received type "number"
01 May 2021 21:02:16.783 iobrokertestsystem trashschedule.0 (6892) State value to set for "trashschedule.0.next.weekday" has to be type "string" but received type "number"
01 May 2021 21:02:16.780 iobrokertestsystem trashschedule.0 (6892) State value to set for "trashschedule.0.type.plastikmüll.nextWeekday" has to be type "string" but received type "number"
01 May 2021 21:02:16.775 iobrokertestsystem trashschedule.0 (6892) State value to set for "trashschedule.0.type.papiermüll.nextWeekday" has to be type "string" but received type "number"
01 May 2021 21:02:16.770 iobrokertestsystem trashschedule.0 (6892) State value to set for "trashschedule.0.type.biomüll.nextWeekday" has to be type "string" but received type "number"
01 May 2021 21:02:16.766 iobrokertestsystem trashschedule.0 (6892) State value to set for "trashschedule.0.type.restmüll.nextWeekday" has to be type "string" but received type "number"
01 May 2021 21:02:15.596 iobrokertestsystem trashschedule.0 (6892) starting. Version 1.1.1 in /opt/iobroker/node_modules/iobroker.trashschedule, node: v12.21.0, js-controller: 3.3.5 
```

Admin 5.0.11
js-controller 3.3.5

**Comment by TheBrain26** [comment]
@klein0r I deleted the objects and the adapter. Afterwards everything was newly furnished and behaved in the same way.
State value to set for "trashschedule.0.next.weekday" has to be type "string" but received type "number"
State value to set for "trashschedule.0.type.altpapier.nextWeekday" has to be type "string" but received type "number"
State value to set for "trashschedule.0.type.bioabfall.nextWeekday" has to be type "string" but received type "number"
State value to set for "trashschedule.0.type.gelbeTonne.nextWeekday" has to be type "string" but received type "number"
State value to set for "trashschedule.0.type.restmüll.nextWeekday" has to be type "string" but received type "number"

Version 1.1.1
node: v12.22.1
js-controller: 3.3.5

**Comment by klein0r** [comment]
@Feuer-sturm Ah, now I understand the message. You initial comment said:

```
trashschedule.0 (969) State value to set for "trashschedule.0.next.weekday" has wrong type "number" but has to be "string"
```

And I thought this means the type has to be changed. Seems like the message has been update, since your latest comment says:

```
trashschedule.0 (6892) State value to set for "trashschedule.0.next.weekday" has to be type "string" but received type "number"
```

Thanks! I will change the type.

**Comment by TheBrain26** [comment]
I deleted the entries and the adapter and then reinstalled and set up. Same problem still

trashschedule.0 | 2021-05-05 08:49:27.152 | info | State value to set for "trashschedule.0.type.restmüll.nextWeekday" has to be type "string" but received type "number"
-- | -- | -- | --
trashschedule.0 | 2021-05-05 08:49:27.149 | info | State value to set for "trashschedule.0.type.altpapier.nextWeekday" has to be type "string" but received type "number"
trashschedule.0 | 2021-05-05 08:49:27.144 | info | State value to set for "trashschedule.0.type.bioabfall.nextWeekday" has to be type "string" but received type "number"
trashschedule.0 | 2021-05-05 08:49:27.140 | info | State value to set for "trashschedule.0.type.gelbeTonne.nextWeekday" has to be type "string" but received type "number"

Adapter V 1.1.3
node: v12.22.1
js-controller: 3.3.8
Admin 5.0.15

**Comment by Feuer-sturm** [comment]
@klein0r I just updated the trashschedule by using "Install or update the adapter from GitHub" to version 1.1.3 and at my system everything is fine now :-)

@TheBrain26 did you update your adapter with the current git version?

**Comment by TheBrain26** [comment]
An installation directly via GIT URL solved the problem. Thanks for your work and the quick support

**Comment by klein0r** [comment]
Makes no sense, since that is exactly the same version?

**Comment by Feuer-sturm** [comment]
@klein0r Yes you are right. I thought that you did only a fix on github which was not released yet. I just removed the adapter and installed 1.1.3 once again using the adapter panel and everything is fine.
