### ISSUE TITLE
Aktulisierung der Abfallzeiten

### ISSUE THREAD

**Issue by derdoerk** [klein0r/ioBroker.trashschedule#69]
Schönen guten Morgen, 

ich benutze den Adapter schon eine Weile und er läuft auch sehr stabil. 

HIerbei benutze ich eine Kalender der von meiner synology bereitgestellt wird. 

Wenn sich an meine Abhollrythmus nichts ändert wenn die Daten auch immer korrekt angezeigt. Jetzt gab es aber öfters durch feiertage mal verschiebung um einen Tag (Diese sind auch im Kalender so eingetrage) der Adapter zeigt mir aber immer den gleichen (Standardtag laut rythmus) an. 

Muss man dort bei der aktualisierung etwas beachten?

Gruß
Dirk

**Comment by jpgorganizer** [comment]
ist bei mir auch so, aber ich glaube das liegt am ical Adapter, vgl.
https://github.com/iobroker-community-adapters/ioBroker.ical/issues/234
oder auch
https://github.com/iobroker-community-adapters/ioBroker.ical/issues/153

**Comment by klein0r** [comment]
Ich kann das Verhalten nicht reproduzieren. Der Adapter holt ja einfach nur die bereitgestellten Termine vom iCal-Adapter ab. Um Termine zu überspringen müsste ja irgendeine Logik dafür implementiert sein - das ist aber nicht der Fall. Es wird einfach der nächste Termin genommen.

Sind die Termine in deinem Kalender Serien-Termine oder alles separate Einträge?

**Comment by jpgorganizer** [comment]
aus meiner Sicht geht es um Ausnahmen in Serienterminen, also eine Serie, z.B. jeden Montag, aber dann eben am Ostermontag doch nicht und deshalb wird nur dieser eine Serientermin auf z.B. den Mittwoch geschoben oder auch aus der Serie gelöscht.
Aber wie oben schon geschrieben, ich halte das für ein Problem des iCal Adapters - but may be I'm wrong

**Comment by derdoerk** [comment]
Vom prinzip ist es so wie jpgorganizer beschrieben hat.

Ich habe für meine tonnen Serientermine (alle 2 Wochen / 4Wochen etc) wo nur einzeltermine aufgrund von Feiertagen verschoben werden. 

Ich habe jetz mal meinen ICAL Adapter auf 1.7.4 aktualisiert, vieleicht ist der Fehler dann weg. 

klein0r: Was brauchst du den, wenn der Fehler nochmal auftritt?

Gruß
Dirk

**Comment by klein0r** [comment]
> klein0r: Was brauchst du den, wenn der Fehler nochmal auftritt?

Erstmal einen Beweis, dass der iCal-Adapter die Termine richtig auswertet und ausgibt, sodass der Fehler im Trashschedule Adapter liegt. Wahrscheinlich bekomme ich die Termine von dort schon falsch und kann da gar nichts machen.
