### ISSUE TITLE
Datenpunkt für "Übernächste" Leerung hinzufügen

### ISSUE THREAD

**Issue by Feuer-sturm** [klein0r/ioBroker.trashschedule#7]
Zusätzlich zur "nächsten Leerung" soll ein Datenpunkt mit der "übernächsten Leerung" erstellt werden, so dass man einfacher die Leerungen auswerten kann, wenn zwei Tonnen direkt nacheinander abgeholt werden.

Ticket stammt aus dieser Diskussion im Forum: https://forum.iobroker.net/topic/22912/vorlagen-ideen-müllplan-view-widget/146

**Comment by m-s-b** [comment]
Könntest du den bzw. die Datenpunkte "übernächste Leerung" auch für die einzelnen Abfalltypen integrieren? Dann hätte man bei niedrigem "Füllstand" gleich im Blick, ob man eine Lieferung auslassen kann.
