### ISSUE TITLE
has to be type "string" but received type "object"

### ISSUE THREAD

**Issue by Pocky2507** [klein0r/ioBroker.trashschedule#70]
Moin,
ich habe hier ein paar Fehlermeldungen.
`
(128290) State value to set for "trashschedule.0.type.plastik.nextDescription" has to be type "string" but received type "object"

(128290) State value to set for "trashschedule.0.type.bio.nextDescription" has to be type "string" but received type "object"

(128290) State value to set for "trashschedule.0.type.restmuell.nextDescription" has to be type "string" but received type "object"

(128290) State value to set for "trashschedule.0.type.papier.nextDescription" has to be type "string" but received type "object"
`
Installiert habe ich Version: 1.1.3

**Comment by klein0r** [comment]
Mit welcher iCal Version?

**Comment by Pocky2507** [comment]
iCal Version: 1.9.3
js-controller: 3.3.11

**Comment by TDCroPower** [comment]
trashschedule.0 | 2021-06-07 13:00:02.928 | info | State value to set for "trashschedule.0.type.schwarzeTonne.nextWeekday" has to be type "string" but received type "number"

auch nextWeekday ist betroffen...
iCal 1.9.3
ks-controller: 3.3.11

die Info log ist aber wohl verkehrt herum, denn der Datenpunkt ist auf string gesetzt und sollte wohl number sein.

**Comment by sokrates-sith** [comment]
ich hab das problem auch seit dem update des js-controllers. aber mit vielen adaptern. manche wurden bereits gefixt.

**Comment by ppb1308** [comment]
Heute Update auf js-controller 3.3.12 und aucxh hier noch die folgenden 4 Einträge im Log:
trashschedule.0
2021-06-11 10:20:05.362	info	State value to set for "trashschedule.0.type.sonderabfälle.nextWeekday" has to be type "string" but received type "number"

trashschedule.0
2021-06-11 10:20:05.361	info	State value to set for "trashschedule.0.type.papiertonne.nextWeekday" has to be type "string" but received type "number"

trashschedule.0
2021-06-11 10:20:05.361	info	State value to set for "trashschedule.0.type.wertstofftonne.nextWeekday" has to be type "string" but received type "number"

trashschedule.0
2021-06-11 10:20:05.360	info	State value to set for "trashschedule.0.type.restmülltonne.nextWeekday" has to be type "string" but received type "number"

**Comment by TDCroPower** [comment]
@ppb1308 sind auch noch nicht gefixt worden vom DEV ;)

**Comment by klein0r** [comment]
@ppb1308 Das wurde in 57eedefd6545a244c837b0595143d22566c3b4c6 schon behoben (siehe #65). Bitte keine Issues mischen. Falls das Problem noch auftritt, einmal alle Datenpunkte unter trashshschedule.0 löschen und den Adapter neu starten.
