### ISSUE TITLE
[Request] use "Calendar" adapter to read calendars via CalDAV protokoll

### ISSUE THREAD

**Issue by uelpenich** [klein0r/ioBroker.trashschedule#71]
Das _TrashSchedule_ Widget für eine sehr gute Lösung, um den nächsten Müllabfuhrtermin anschaulich und  platzsparend zu visualisieren. 
**Is your feature request related to a problem? Please describe.**
Das TrashSchedule Widget übernimmt die Informationen, die von dem Adapter **ical** aus Google und ähnlichen Kalendern extrahiert werden. Leider stellen nicht alle E-Mail Provider die ics Datei zum automatischen Download zur Verfügung. 

**Describe the solution you'd like**
Der Adapter "Calendar" https://github.com/WLAN-Kabel/ioBroker.calendar kann die Kalendereinträge vieler E-Mail Provider (meiner setzt Open-xchange ein) über CalDAV auslesen (google Kalender geht auch, möchte ich für mich aber nicht einsetzen). 

**Describe alternatives you've considered**
Kann das TrashSchedule Widget so erweitert werden, dass es auch auf die Informationen des Adapters "Calendar" zugreifen kann?

**Additional context**
Hier ist ein Beispiel der Objekte, die von dem Adapter calendar angelegt werden:
![grafik](https://user-images.githubusercontent.com/63613798/124922835-2e81ab00-dffa-11eb-82c6-293763d22dc5.png)
Wert des Kalender Events am 2021-07-14:
![grafik](https://user-images.githubusercontent.com/63613798/124922862-36414f80-dffa-11eb-94cc-ea52fafacaae.png)
PS: ich habe die Abfuhrtermine im Kalender als Ganztags-Ereignisse eingetragen, deshalb keine Uhrzeit im Eintrag.

**Comment by klein0r** [comment]
Da der Carlender-Adapter seit Jahren verwaist und nix mehr in dem Projekt passiert, möchte ich ungern Zeit investieren. Das bedeutet ja nur wieder mehr Support, mehr Doku schreiben und natürlich auch mehr Fehlerquellen.

**Comment by uelpenich** [comment]
Vielen Dank für diese Info. Ich habe einen manuellen Work-around gefunden und kann damit leben. 
Schön (und danke), dass Sie ihre Zeit in produktivere Projekte investieren.
