### ISSUE TITLE
Text aus Beschreibung einbinden

### ISSUE THREAD

**Issue by tottiMG** [klein0r/ioBroker.trashschedule#72]
ich hätte da noch einen Erweiterungswunsch.

Und zwar geht es darum, dass ich in einem Mehrfamilienhaus wohne, wo jede Partei abwechselnd dran ist die jeweilige Tonnen rauszustellen.

Ich habe in meinem Google-Kalender unter Beschreibung den Namen derjenigen Mietpartei eingetragen, welche mit dem rausstellen der Tonnen dran ist.

Nun möchte ich gerne eine Nachricht vom IOBroker bekommen, wenn mein Name in der Beschreibung steht. Kannst du dafür einen Datenpunkt einbinden, wo der Text aus der Beschreibung übernommen wird?

**Comment by klein0r** [comment]
Das passiert doch eigentlich schon unter "nextDescription"?

**Comment by tottiMG** [comment]
Danke!! Hatte ich total übersehen!

**Comment by tottiMG** [comment]
Ok, hatte ich da nicht gesehen. Wäre mir aber unter **trashschedule.0.next** oder **trashschedule.0.nextAfter** lieber gewesen

**Comment by klein0r** [comment]
Und was soll ich darstellen? Eine Liste mit allen Texten aus allen nächsten Events? Kommasepariert?

**Comment by tottiMG** [comment]
So wie es jetzt ist, ist es ok. So kann ich es ja auch umsetzen mit Blockly

Mein Wunsch wäre nur gewesen, dass "nextDescription" auch bei "next" und "nextAfter" gewesen wären.

Aber wie schon geschrieben ist so auch ok
