### ISSUE TITLE
Nach ical Update 1.10.0 Trashschedule ohne Funktion

### ISSUE THREAD

**Issue by JBSullivan** [klein0r/ioBroker.trashschedule#73]
Es gab ein neues ical Update auf 1.10.0 seit dem funktioniert die letzte Version von Trashschedule nicht mehr (bleibt gelb)

`
<html>
<body>

trashschedule.0 | 2021-07-16 17:50:01.064 | error | (12724) no events found in iCal instance - check configuration and restart adapter
-- | -- | -- | --

</body>
</html>`

**Comment by klein0r** [comment]
Danke, muss ich mir mal in Ruhe anschauen

**Comment by klein0r** [comment]
Ah, ich sehe schon:

``IMPORTANT: data.table is now a stringified array!! Consider when using this value!``
