### ISSUE TITLE
Update ical auf v1.10.0 - no events found in iCal instance - check configuration and restart adapter

### ISSUE THREAD

**Issue by kueppert** [klein0r/ioBroker.trashschedule#74]
Hi,
ich habe heute dem ical das neue Update verpasst. Seitdem erhalte ich folgende Fehlermeldung:
`
<html>
<body>

trashschedule.0 | 2021-07-16 23:20:03.830 | error | no events found in iCal instance - check configuration and restart adapter
-- | -- | -- | --

</body>
</html>

Im Changelog steht folgendes bei ical zur neuen Version:
``IMPORTANT:` data.table is now a stringified array!! Consider when using this value!`

Kann es daran liegen, das der Trash keine Events mehr findet? Unter ical.0 sind auf jeden Fall noch welche...

**Comment by klein0r** [comment]
Duplicate of #73
