### ISSUE TITLE
Version 1.1.1 isn't compatible with stable ical v. 1.11.2

### ISSUE THREAD

**Issue by meistermopper** [klein0r/ioBroker.trashschedule#75]
With this combination i get the error log
<html><body>

trashschedule.0 | 2021-08-02 14:14:18.852 | error | (3192) no events found in iCal instance - check configuration and restart adapter
-- | -- | -- | --

</body>
</html>

No problems with ical 1.9.3!

**Comment by Rene5555** [comment]
Dem muss ich mich anschließen. Ebenfalls Version 1.1.1

**Comment by firebowl** [comment]
Jo hab das gleiche Problem seit dem Update.

**Comment by klein0r** [comment]
Deswegen gibt es ja auch schon 1.2.0 ? 😄 
Update bald die stable version
