### ISSUE TITLE
maybe add an ical dependency?

### ISSUE THREAD

**Issue by Apollon77** [klein0r/ioBroker.trashschedule#76]
Because it seems that the latest ical updates broke trashschedule maybe think about adding a "common.globalDependencies" section to io-package which refers to the compatible ical version?

**Comment by klein0r** [comment]
I thought about that. But how should I know to which version in the future it will work? Otherwise I have to release a new version with updated `globalDependencies` for every new release of iCal.

- Worked until: 1.9.x
- Doesn't work with: 1.10.x
- Doesn't work with: 1.11.x
- ...

**Comment by Apollon77** [comment]
What exactly was the reason for the break ... so which change? Was itthe restructuring of the events? Then honestly ... yes this should have been a 2.x but was not realized ...

**Comment by klein0r** [comment]
The data state (which contains all events) have been changed from object to JSON string.

**Comment by Apollon77** [comment]
ahhh ...ok thats basically a bugfix because also "Object" was kind of unsupported in general and was "the wrong way to do it" ... also that should never happen again :-)

**Comment by Apollon77** [comment]
ber kannst aucf jeden fall eine globalDe mit ical >=1.11.0 machen dann weisst Du das das objekt so ist wie es jetzts ein soll

**Comment by klein0r** [comment]
In 1.3.0 implementiert
