### ISSUE TITLE
IoBroker keine Installation

### ISSUE THREAD

**Issue by Ron979** [klein0r/ioBroker.trashschedule#77]
### The problem

Ich bekomme leider den Adapter nicht mehr installiert. System ist eine Synology Diskstation 1621+ mit Docker & IoBroker Kann man mir da helfen? Vielen Dank für den tollen Adapter
![trashinstall](https://user-images.githubusercontent.com/88034221/128546118-0cffdc20-412e-44e2-b2bf-2e629edcc9d8.jpg)
![trashinstall](https://user-images.githubusercontent.com/88034221/128546147-708fd87b-acf0-4445-8547-b88927f380ca.jpg)

### Version of ioBroker js-controller

Version v12.22.4

### Version of Adapter

1.2.0

### Operating system running ioBroker

Linux

### Checklist of files to include below

- [X] iobroker.current.log (Please share the logs in debug mode)
- [ ] Contents of the JavaScript browser console (always include in cases of issues with the user interface)

### Additional information & file uploads

Ich bekomme leider den Adapter nicht mehr installiert. System ist eine Synology Diskstation 1621+ mit Docker & IoBroker Kann man mir da helfen? Vielen Dank für den tollen Adapter

![trashinstall](https://user-images.githubusercontent.com/88034221/128546802-f27071b7-5b94-4a3f-befa-ac216fc6bbd5.jpg)

**Comment by klein0r** [comment]
Einfach die Fehlermeldung lesen ;) Du nutzt nodejs 10.24.1, aber der Adapter braucht mindestens nodejs 12.
Das ist übrigens auch die empfohlene Version für den Betrieb vom ioBroker aktuell.
