### ISSUE TITLE
Anzeigefehler Objektbaum mit Admin 5

### ISSUE THREAD

**Issue by crunchip77** [klein0r/ioBroker.trashschedule#78]
Mit neuer Admin Oberfläche(dunkles Design) wird der Pfad trashschedule.0.type so angezeigt, getestet mit Chrome und FF
![image](https://user-images.githubusercontent.com/41550245/128697217-466331cd-4bd1-4947-b0e4-11ade52b4dfc.png)

### Version of ioBroker js-controller

3.3.15

### Version of Adapter

1.2.0

### Operating system running ioBroker

Linux

### Checklist of files to include below

- [X] iobroker.current.log (Please share the logs in debug mode)
- [ ] Contents of the JavaScript browser console (always include in cases of issues with the user interface)

**Comment by klein0r** [comment]
So werden eingefärbte Datenpunkte halt im Admin dargestellt. Da kann ich wenig machen 😄 
Bitte einen Issue im Admin-Projekt öffnen.

**Comment by Feuer-sturm** [comment]
Issue in admin adapter: https://github.com/ioBroker/ioBroker.admin/issues/1078

**Comment by klein0r** [comment]
Nochmal zur Sicherheit:

- Dass der Objekt-Baum mit eingefärbt wird, ist generell so gewollt
- Dafür wird ein Feature vom Datenpunkt genutzt (common.color), welcher es erlaubt, eigene Farben festzulegen für den Admin
- Leider führt das in manchen Admin-Themes dazu, dass ein weißer Hintergrund eingefügt wird ** - und DAS ist der Fehler**

**Comment by crunchip77** [comment]
Das mit (common.color) wusste ich nicht, ist m.M. eigentlich in der Objektbaumansicht auch gar nicht nötig, für den Wert ja, aber nicht für den Datenpunkt selbst.
Richtig, der weiße Hintergrund ist da etwas störend ;)

**Comment by klein0r** [comment]
Naja, warum sollte man Features nicht nutzen. Wenn man ein helleres Theme auswählt, dann sieht das ja auch wieder gut aus.

**Comment by klein0r** [comment]
Das sind ja auch System-Datenpunkte, da wurde scheinbar eine Ausnahme gemacht.
Laut Bluefox ist es ja sogar Absicht, dass der Hintergrund weiß wird (um den Kontrast zur Farbe zu erhöhen).

Schön finde ich das auch nicht, aber wenigstens kann man den Datenpunkt dann in jedem Fall lesen.
Optimal wäre natürlich, wenn der Admin5 das aktuelle Theme auswerten würde, und nur dann die Farbe vom Hintergrund anpassen, wenn der Kontrast sehr schlecht ist. Gelb wäre bei einem dunklen Theme ja z.B. wunderbar lesbar, bei einem hellen Theme müsste dann der Hintergrund schwarz werden.

Allerdings ist das wahrscheinlich etwas Overkill für ein bisschen Kosmetik.

**Comment by crunchip77** [comment]
Die Antwort gefällt mir besser ;)
alles gut, dachte nur, wie Anfangs erwähnt, dass da eventuell ein Fehler vorliegen könnte, da mir weiter kein einziger Ordner/Datenpunkt angezeigt wird, der sich so verhält in der Objektansicht.
