### ISSUE TITLE
Vis Template wird nicht auf iPad2 angezeigt

### ISSUE THREAD

**Issue by winterson0** [klein0r/ioBroker.trashschedule#8]
WebServer V2.4.10
Vis V1.1.10

Das Vis Trash Template wird zwar im Browser angezeigt, aber auf einem iPad2 ist es nicht zu sehen.

**Comment by klein0r** [comment]
Mit welchem Browser (in welcher Version) wird die Seite denn aufgerufen

**Comment by winterson0** [comment]
> 
> 
> Mit welchem Browser (in welcher Version) wird die Seite denn aufgerufen

Es handelt sich um Safari unter iOS 9.3.6

**Comment by klein0r** [comment]
Mh, SVG Dateien sollten dort eigentlich unterstützt werden.
Ich habe leider kein so altes iPad zum testen.

**Comment by winterson0** [comment]
> Mh, SVG Dateien sollten dort eigentlich unterstützt werden.
> Ich habe leider kein so altes iPad zum testen.

Also ich habe es heute getestet. Auf einem iPad3 läuft es. Ich denke es macht keinen Sinn das man den Fehler für das iPad2 behebt, da die neuen Admin, Web und socketio Adapter auch nicht mehr auf dem iPad2 lauffähig sind.

**Comment by klein0r** [comment]
Genau, das iPad 2 ist ja auch mit den neueren socket.io Versionen schon rausgeflogen. Ich mache hier mal zu

**Comment by KoljaW** [comment]
Auf dem iPad3 geht es nun auch nicht mehr. Sonst geht noch alles. Vielleicht kann man da doch noch was machen?
