### ISSUE TITLE
[Widget] Falsche Höhe bei "Anzahl Tage bis zur nächsten Leerung"-Beschriftung für Biotonne

### ISSUE THREAD

**Issue by robson80** [klein0r/ioBroker.trashschedule#80]
Hallo zusammen,
der Titel sagt es eigentlich schon aus. Es geht um eine Beschriftung im Vis-Widget.
Die Zahl, welche die Tage bis zur nächsten Lieferung für die Biotonne darstellt, ist ggü. den anderen Tonnentypen leicht nach oben versetzt.

![Unbenannt-1](https://user-images.githubusercontent.com/42472672/128759371-8f2d44ac-a352-4e6a-b36f-b8f8b126cf3c.jpg)

Nicht dramatisch, jedoch unschön.

Vielen Dank für den Adapter und das tolle Widget.

VG

**Comment by robson80** [comment]
Geschlossen. Nachdem ich das Widget nochmals in die Vis reingezogen habe, passt es auf einmal.

**Comment by klein0r** [comment]
Das liegt daran, dass der Titel bei Dir so lang war, dass er in eine zweite Zeile gerutscht ist.
Generell hat das Widget noch ein paar Macken in solchen Situationen - muss ich nochmal in Ruhe ran.
