### ISSUE TITLE
[Request] Ignore warnings

### ISSUE THREAD

**Issue by wolflu05** [klein0r/ioBroker.trashschedule#82]
### Is your feature request related to a problem? Please describe.

I'm always frustrated when whenn I go to the logs and see such warnings. It would be a good choice to prevent that. E.g. in my town there are also collections that are not repeated so often, such as the Christmas tree collection or the pollutant collection.
![image](https://user-images.githubusercontent.com/76838159/129846827-296a232e-c09e-4890-a05f-928d76c8d62c.png)

### Describe the solution you'd like

I already read in issue #49 that you want to keep that modules settings simple for beginners. But what about adding a checkbox like `extended settings` which obens a area with the suggested options in #49 and a checkbox to prevent that messy warnings.

**Comment by klein0r** [comment]
The problem is: More settings => more possible cases => more to explain.
Leads to more support and more of my time.

Even the current settings are to complicated for some people and I get a lot of emails with very simple questions...

**Comment by wolflu05** [comment]
OK. Then I will close this issue.
