### ISSUE TITLE
Set loglevel for 'no events matches type' from 'warn' to 'info'

### ISSUE THREAD

**Issue by A30BL** [klein0r/ioBroker.trashschedule#84]
**Is your feature request related to a problem? Please describe.**
Hier vor Ort gibt es bestimmte Müllsammlungen, die nur alle halbe Jahre, auch nur einmal im Jahr oder sogar nur nach Abruf mit einer Vorlaufzeit von 1-2 Monaten (z.B. Sperrmüll) stattfinden. Diese Termine verursachen alle 30 Minuten fast dauerhaft Einträge im Log mit der Stufe 'warn' wie z.B.:
`no events matches type "Sperrmüll" with match "Sperr". Check configuration of iCal (increase preview) and trashschedule!`

**Describe the solution you'd like**
Wenn ich es richtig gelesen habe, willst du den Adapter ja nicht um schreiben, so dass man diese Warnung ausstellen kann.
Hier den Preview auf über ein Jahr zu setzen, halte ich nicht für wirklich sinnvoll.
Daher fände ich es gut, wenn du die oben genannte Fehlermeldung auf die Stufe 'info' heruntersetzen könntest.
Über die Basiseinstellungen in ioBroker lässt sich ja die Standardprotokollstufe für neue Instanzen setzen. Wählt man hier 'warn', so werden ja scheinbar nur die wirklich wichtigen Dinge (warn, error) geloggt. So könnte man dann deinen Adapter auch etwas schweigsamer bekommen. Wer diese Meldungen trotzdem loggen möchte, setzt in dann halt die Standardprotokollstufe auf 'info'.

**Comment by klein0r** [comment]
Das wurde bewusst eingebaut, weil ich immer wieder Anfragen zu Themen bekomme, dass etwas nicht funktioniert. Und dann stimmt die Konfiguration nicht und das Problem lag nie am Adapter. Deswegen probiere ich so viel wie möglich im Log als Infos mitzugeben.

Sonst müsste ich mal eine Option einführen, welche diese Info verschwinden lässt.

**Comment by klein0r** [comment]
Ich bin gespannt, wann der erste hier aufschlägt 😄 Dann verweise ich hierher

**Comment by A30BL** [comment]
Inzwischen bin ich von ioBroker zu Home Assistant gewechselt. Nicht alles, jedoch das meiste gefällt mir bei Home Assistant besser; unter anderem gibt es dort auch verschiedene Müllkalender. Die Einrichtung war einfach und nun muss ich mich auch nicht mehr mir den nicht notwendigen Fehlermeldungen herumschlagen.
 

 


Ich bin gespannt, wann der erste hier aufschlägt 😄 Dann verweise ich hierher
