### ISSUE TITLE
Nach Update auf 1.3.1 Widget verschwunden

### ISSUE THREAD

**Issue by Flyor** [klein0r/ioBroker.trashschedule#87]
Ich habe das Update auf die 1.3.1 gemacht, der Adapter bzw. die Instanz ist auch vorhanden und grün, Datenpunkte unter Objekten werden auch wie gehabt angelegt. Allerdings ist das Widget aus meiner VIS verschwunden. Beim Versuch es erneut anzulegen, habe ich festgestellt dass es nicht mehr da ist. Bin ich ein bedauerlicher Einzelfall?!

**Comment by Negalein** [comment]
mit 1.3.2 sind sie wieder da.

**Comment by klein0r** [comment]
Ich würde Dich demnächst bitten

- zu prüfen, ob Du wirklich die aktuellste Version nutzt
- ob es schon andere Issues zu dem Thema gibt
- Falls nicht, das Bug Report Template zu nutzen

Am Link zum Forum bist Du ja automatisch beim Bug anlegen auch vorbei gekommen :) Da lohnt es sich auch einen kurzen Blick zu riskieren.
