### ISSUE TITLE
Log full of errors after upgrade to 1.3.4

### ISSUE THREAD

**Issue by Dragon0501** [klein0r/ioBroker.trashschedule#88]
### The problem

`

host.iobroker | 2021-11-15 10:57:45.926 | warn | Do not restart adapter system.adapter.trashschedule.0 because restart loop detected
-- | -- | -- | --
host.iobroker | 2021-11-15 10:57:45.926 | info | Restart adapter system.adapter.trashschedule.0 because enabled
host.iobroker | 2021-11-15 10:57:45.925 | error | instance system.adapter.trashschedule.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
host.iobroker | 2021-11-15 10:57:45.925 | error | Caught by controller[1]: at Trashschedule.updateByCalendarTable (/opt/iobroker/node_modules/iobroker.trashschedule/main.js:419:52)
host.iobroker | 2021-11-15 10:57:45.925 | error | Caught by controller[1]: at Trashschedule.setStateAsync (/opt/iobroker/node_modules/iobroker.js-controller/lib/tools.js:1651:16)
host.iobroker | 2021-11-15 10:57:45.925 | error | Caught by controller[1]: at new Promise (<anonymous>)
host.iobroker | 2021-11-15 10:57:45.925 | error | Caught by controller[1]: at /opt/iobroker/node_modules/iobroker.js-controller/lib/tools.js:1652:16
host.iobroker | 2021-11-15 10:57:45.925 | error | Caught by controller[1]: at Trashschedule.setState (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:6091:21)
host.iobroker | 2021-11-15 10:57:45.925 | error | Caught by controller[1]: at validateSetStateObjectArgument (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:6004:23)
host.iobroker | 2021-11-15 10:57:45.925 | error | Caught by controller[1]: Error: The state contains the forbidden properties params!
host.iobroker | 2021-11-15 10:57:45.924 | error | Caught by controller[0]: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
trashschedule.0 | 2021-11-15 10:57:45.309 | warn | Terminated (UNCAUGHT_EXCEPTION): Without reason
trashschedule.0 | 2021-11-15 10:57:45.287 | error | The state contains the forbidden properties params!
trashschedule.0 | 2021-11-15 10:57:45.286 | error | Error: The state contains the forbidden properties params! at validateSetStateObjectArgument (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:6004:23) at Trashschedule.setState (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:6091:21) at /opt/iobroker/node_modules/iobroker.js-controller/lib/tools.js:1652:16 at new Promise (<anonymous>) at Trashschedule.setStateAsync (/opt/iobroker/node_modules/iobroker.js-controller/lib/tools.js:1651:16) at Trashschedule.updateByCalendarTable (/opt/iobroker/node_modules/iobroker.trashschedule/main.js:419:52)
trashschedule.0 | 2021-11-15 10:57:45.264 | error | unhandled promise rejection: The state contains the forbidden properties params!
trashschedule.0 | 2021-11-15 10:57:45.262 | error | Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
host.iobroker | 2021-11-15 10:57:42.919 | info | instance system.adapter.trashschedule.0 started with pid 3009
host.iobroker | 2021-11-15 10:57:12.863 | info | Restart adapter system.adapter.trashschedule.0 because enabled

`

Adapter stays red after update to 1.3.4

1.3.3 works without errors

### Version of ioBroker js-controller

3.3.18

### Version of Adapter

1.3.4

### Operating system running ioBroker

Linux Proxmox VM

### Checklist of files to include below

- [X] iobroker.current.log (Please share the logs in debug mode)
- [ ] Contents of the JavaScript browser console (always include in cases of issues with the user interface)

**Comment by klein0r** [comment]
Fixed in 1.3.5
