### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by BlackScript** [klein0r/ioBroker.trashschedule#89]
### The problem

Instanz kann nicht hinzugefügt werden

### Version of ioBroker js-controller

12.22.6

### Version of Adapter

1.3.5

### Operating system running ioBroker

docker

### Checklist of files to include below

- [X] iobroker.current.log (Please share the logs in debug mode)
- [X] Contents of the JavaScript browser console (always include in cases of issues with the user interface)

### Additional information & file uploads

$ iobroker add trashschedule auto --host iobroker

Adapter "system.adapter.vis.0" restarted.

host.iobroker create instance trashschedule

/opt/iobroker/node_modules/iobroker.js-controller/lib/setup/setupInstall.js:1005 Object.keys(adapterConf.instanceObjects[i].common.name).forEach(lang => adapterConf.instanceObjects[i].common.name[lang] = adapterConf.instanceObjects[i].common.name.replace('%INSTANCE%', instance)); ^TypeError: adapterConf.instanceObjects[i].common.name.replace is not a function at /opt/iobroker/node_modules/iobroker.js-controller/lib/setup/setupInstall.js:1005:211 at Array.forEach (<anonymous>) at Immediate.<anonymous> (/opt/iobroker/node_modules/iobroker.js-controller/lib/setup/setupInstall.js:1005:101) at processImmediate (internal/timers.js:463:21)

ERROR: Process exited with code 1

**Comment by klein0r** [comment]
Welche js-controller Version läuft denn?

**Comment by BlackScript** [comment]
ist das nicht die angegebene node.js version ? v12.22.6

**Comment by klein0r** [comment]
Nein, das ist die nodejs-Version.
Ich möchte die Version vom Controller wissen, also dem Kern-Prozess von ioBroker. Findest Du z.B. unter "Hosts" im Admin Adapter.

**Comment by BlackScript** [comment]
3.3.18

**Comment by klein0r** [comment]
Ist mit js-controller 3.3.19 gefixt
