### ISSUE TITLE
Instanz startet nicht korrekt

### ISSUE THREAD

**Issue by FRYYYYYY** [klein0r/ioBroker.trashschedule#9]
Die Instanz startet nicht korrekt:

![image](https://user-images.githubusercontent.com/13643787/76660609-9399cd80-6579-11ea-93e7-31d97898b1d5.png)

Alle Objekte bleiben leer. iCal-Instanz ist konfiguriert, Abfall-Typen ebenfalls.

trashschedule: 0.0.5
admin: 4.0.5
js-controller: 2.2.10
ical: 1.7.1

**Comment by klein0r** [comment]
Ich nehme an, dass Du alles aus der Readme bereits geprüft hast? Der Adapter bleibt gelb, wenn er keine Termine finden kann.

Viele haben im iCal-Adapter bereits "Ereignisse" gepflegt. Wenn man diese dort anlegt, dann filtert der iCal-Adapter die treffenden Termine bereits heraus. Dadurch sind diese nicht mehr für andere Adapter und Scripts lesbar und die Liste ist leer.

Wichtig ist daher, im Ergenisse-Tab im iCal-Adapter überall den Haken bei "anzeigen" zu setzen (dann werden die Termine nicht mehr gefiltert) oder eben die Ereignisse dort zu löschen

**Comment by FRYYYYYY** [comment]
Ja, hast recht. Sorry. "Anzeigen" fehlte. Jetzt weiß ich auch, was das bedeutete.
