### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by akoerth** [klein0r/ioBroker.trashschedule#93]
### The problem

Hallo zusammen, #ich kann keinen 2 Trashscheduler installieren. im Admin Bereich findet er dann keinen Indey Bereich und ich kann somit keine EInstellungen vornehmen.
![grafik](https://user-images.githubusercontent.com/97634891/151668348-ce26472a-6230-4c1d-acd0-e3fc86973360.png)
![grafik](https://user-images.githubusercontent.com/97634891/151668383-45f754ee-006e-4810-8a25-2437a7f7b8c5.png)

### Version of nodejs

14.18.3

### Version of ioBroker js-controller

5.2.13

### Version of Adapter

1.4.1

### Operating system running ioBroker

Linux

### Checklist of files to include below

- [X] iobroker.current.log (Please share the logs in debug mode)
- [ ] Contents of the JavaScript browser console (always include in cases of issues with the user interface)

**Comment by klein0r** [comment]
Adapter has no admin 4 support. Please use admin 5 UI

**Comment by akoerth** [comment]
HI klein0r, 
my Admin version is 5.2.3 and not version 4.
I cannot install more instances from this adapter see error below.
![grafik](https://user-images.githubusercontent.com/97634891/151674984-153dac47-ae8e-45eb-a235-36e6dee1e1eb.png)
If i delete the Adapter an reinstall this, i get the same Error.
Please Help

**Comment by klein0r** [comment]
You have to uncheck „use old Admin 4 UI“ in your admin Instance.
As already said, Admin 4 support was dropped

**Comment by akoerth** [comment]
HI, 
can you tell me where I can find this setting. In the admin adapter this setting is not present. 

Thank you

**Comment by klein0r** [comment]
UNCHECK this

<img width="1094" alt="Screenshot 2022-01-30 at 11 24 12" src="https://user-images.githubusercontent.com/1959049/151695853-97849895-1aee-4890-a00a-ebe7873ef120.png">

**Comment by akoerth** [comment]
Thank you
in Chrome browser it did not show me this setting. Better said the scrollbar. Only when I was in Edge I could see it. 
Now another instance works. 
Have a nice rest of sunday.
regards Andreas
