### ISSUE TITLE
Modul hängen geblieben - bei Aufruf Einstellunge Gui-Error

### ISSUE THREAD

**Issue by erlebenmedia** [klein0r/ioBroker.trashschedule#96]
### The problem

Bug tritt in stable und beta auf.
IoB ist aktuell.
Fehler tritt nur in Trash Schedule auf. 
Installation eines zweiten Adapters möglich, Verhalten jedoch identisch.
Fehler Ende Januar erstmals aufgetreten.
Logging zeigt im Debug keinerlei Einträge

![image](https://user-images.githubusercontent.com/99345230/153373934-2bcdf1b5-ba8a-41c2-8ea4-53d85065f5ef.png)

![image](https://user-images.githubusercontent.com/99345230/153373124-57f632f3-c46f-4ac4-bc94-35128d29c72c.png)

react-dom.production.min.js:216 Error: Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=object%20with%20keys%20%7Ben%2C%20de%2C%20ru%2C%20pt%2C%20nl%2C%20fr%2C%20it%2C%20es%2C%20pl%2C%20zh-cn%7D for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at Mc (react-dom.production.min.js:140:47)
    at d (react-dom.production.min.js:144:29)
    at v (react-dom.production.min.js:146:132)
    at react-dom.production.min.js:150:224
    at Ro (react-dom.production.min.js:176:171)
    at Ui (react-dom.production.min.js:271:134)
    at Cl (react-dom.production.min.js:250:347)
    at _l (react-dom.production.min.js:250:278)
    at El (react-dom.production.min.js:250:138)
    at ml (react-dom.production.min.js:243:163)

### Version of nodejs

v14.19.0

### Version of ioBroker js-controller

v4.06

### Version of Adapter

1.4.2

### Operating system running ioBroker

Linux Ubuntu 20.04 - 5.13.0-28 unter Proxmoxx

### Checklist of files to include below

- [ ] iobroker.current.log (Please share the logs in debug mode)
- [ ] Contents of the JavaScript browser console (always include in cases of issues with the user interface)

**Comment by erlebenmedia** [comment]
sowohl bei 5.1.25 stable, als auch der v5.3.0 beta

**Comment by klein0r** [comment]
Dann muss das irgendwie mit deiner Config zusammenhängen. Kannst Du mir mal die Instanz-Konfiguration geben?

Bitte mal auf den Shell ausführen und Ausgabe hier teilen:

```
iobroker object get system.adapter.trashschedule.0
```

**Comment by klein0r** [comment]
Wobei das ziemlich unlogisch ist, weil der Fehler ja aus dem "GitHubInstallDialog" kommt.
Hast Du den Adapter über GitHub installiert?

**Comment by klein0r** [comment]
Und was ist der Grund dafür? Das ist nie eine gute Idee.
Dafür gibt es hier keinen Support, weil Du einen undefinierten Stand installiert hast.

Bitte Adapter löschen und ganz normaler über das Repo installieren.

**Comment by erlebenmedia** [comment]
Also, ich habe gerade noch einmal nachgesehen. Installtion ist tatsächlich über die ioBroker Repo passiert.
Ich habe auch noch einmal zwei neue Adapter darüber installiert. Selber Fehler.

**Comment by erlebenmedia** [comment]
Ich habe den Adapter jetzt noch einmal komplett deinstalliert, ein Update und Upgrade des vollen Systems mit anschließendem Neustart gemacht. Es wurden keine Komponenten aktualisiert. Aber der Adapter läuft jetzt wieder. 
Danke für den Support. Ticket kann als gelöst markiert werden.
