### ISSUE TITLE
Trennzeichen "und" verbindet den Text ohne Trennzeichen

### ISSUE THREAD

**Issue by GrayDeathNBG** [klein0r/ioBroker.trashschedule#99]
### The problem

Wenn man das Trennzeichen von komma auf und umstellt wird der Text als "RestmülltonneundBiotonne" statt "Restmülltonne und Biotonne" erstellt.

### Version of nodejs

14.19.0

### Version of ioBroker js-controller

4.0.15

### Version of Adapter

1.4.1

### Operating system running ioBroker

Linux Debian Buster

### Checklist of files to include below

- [X] iobroker.current.log (Please share the logs in debug mode)
- [ ] Contents of the JavaScript browser console (always include in cases of issues with the user interface)

**Comment by klein0r** [comment]
Ja, das ist Absicht. Dann kann man auch ein Komma nutzen.
Allerdings entfernt der aktuelle Admin wohl Leerzeichen drumherum. Das muss ich noch genauer testen.

**Comment by GrayDeathNBG** [comment]
ja genau, das mit den Leerzeichen habe ich auch schon versucht ...

**Comment by klein0r** [comment]
Habe mal einen Issue geöffnet und warte auf Feedback. https://github.com/ioBroker/ioBroker.admin/issues/1355
